import { useEffect, useState } from "react";
import { Camera, UserRound } from "lucide-react";
import { createSignedFileUrl, deletePrivateFile, uploadPrivateFile, upsertRow } from "../../services/database";
import { requireSupabase } from "../../lib/supabase";
import type { Profile } from "../../types";

type Props = { profile: Profile; userId?: string; onSaved: () => Promise<void>; onToast: (toast: { type: "success" | "error" | "warning"; message: string }) => void };

export default function ProfileIdentityCard({ profile, userId, onSaved, onToast }: Props) {
  const supabase = requireSupabase(); const [imageUrl,setImageUrl]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;if(!profile.profile_image_path){setImageUrl("");return()=>{active=false;};}void createSignedFileUrl("avatars",profile.profile_image_path).then((url)=>{if(active)setImageUrl(url);}).catch(()=>{if(active)setImageUrl("");});return()=>{active=false;};},[profile.profile_image_path]);
  async function uploadAvatar(file:File){if(!userId)throw new Error("Please sign in again before uploading a profile photo.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Use a JPG, PNG, or WEBP image.");if(file.size>2*1024*1024)throw new Error("Profile photos must be 2 MB or smaller.");const extension=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const path=`${userId}/${crypto.randomUUID()}.${extension}`;setBusy(true);try{const uploaded=await uploadPrivateFile("avatars",path,file);await upsertRow("profile",{user_id:userId,profile_image_path:uploaded},{onConflict:"user_id"});if(profile.profile_image_path&&profile.profile_image_path!==uploaded)await deletePrivateFile("avatars",profile.profile_image_path).catch(()=>undefined);const signed=await createSignedFileUrl("avatars",uploaded);setImageUrl(signed);await onSaved();onToast({type:"success",message:"Profile photo updated."});}finally{setBusy(false);}}
  async function removeAvatar(){if(!userId||!profile.profile_image_path)return;setBusy(true);try{await deletePrivateFile("avatars",profile.profile_image_path);const {error}=await supabase.from("profiles").update({profile_image_path:null}).eq("user_id",userId);if(error)throw error;setImageUrl("");await onSaved();onToast({type:"success",message:"Profile photo removed."});}catch(error){onToast({type:"error",message:error instanceof Error?error.message:"Profile photo could not be removed."});}finally{setBusy(false);}}
  return <section className="card panel profile-identity-card"><div className="profile-photo-wrap">{imageUrl?<img src={imageUrl} alt={`${profile.full_name||"Athlete"} profile`} className="profile-photo" style={{width:96,height:96,borderRadius:"50%",objectFit:"cover"}}/>:<div className="profile-photo placeholder" style={{width:96,height:96,borderRadius:"50%",display:"grid",placeItems:"center"}}><UserRound size={34}/></div>}<label className="profile-photo-button btn" aria-label="Change profile photo"><Camera size={15}/> {busy?"Saving...":"Change photo"}<input type="file" accept="image/jpeg,image/png,image/webp" hidden disabled={busy} onChange={(e)=>{const file=e.target.files?.[0];if(file)void uploadAvatar(file).catch((error)=>onToast({type:"error",message:error instanceof Error?error.message:"Profile photo could not be uploaded."}));e.currentTarget.value="";}}/></label>{profile.profile_image_path&&<button type="button" className="plain danger" onClick={()=>void removeAvatar()} disabled={busy}>Remove</button>}</div><div><span className="eyebrow">Profile identity</span><h3>{profile.full_name||"Athlete"}</h3><p>Use a clear profile photo so coaches and teammates can recognize your account.</p><div className="badge-row">{profile.verified_athlete&&<span className="verified">Verified Athlete</span>}{profile.founder_badge&&<span className="verified">Founder</span>}</div></div></section>;
}
