import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors } from '@/constants/theme';

export const c=Colors.dark;
export function Screen({children,scroll=true,bottomBar}:{children:React.ReactNode;scroll?:boolean;bottomBar?:React.ReactNode}){
 const body=<View style={s.wrap}>{children}</View>;
 return <SafeAreaView style={s.screen} edges={['top']}>{scroll?<View style={{flex:1}}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>{body}</ScrollView>{bottomBar}</View>:<View style={{flex:1}}>{body}{bottomBar}</View>}</SafeAreaView>;
}
export function Header({eyebrow,title,subtitle,right,back=false}:{eyebrow:string;title:string;subtitle?:string;right?:React.ReactNode;back?:boolean}){const router=useRouter();return <View style={s.header}>{back?<Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹  BACK</Text></Pressable>:null}<View style={s.headerRow}><View style={{flex:1,gap:4}}><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.title}>{title}</Text>{subtitle?<Text style={s.subtitle}>{subtitle}</Text>:null}</View>{right}</View></View>}
export function Section({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <View style={s.sectionWrap}><View style={s.sectionHead}><Text style={s.section}>{title}</Text>{action}</View>{children}</View>}
export function Card({children,accent=false}:{children:React.ReactNode;accent?:boolean}){return <View style={[s.card,accent&&s.accentCard]}>{children}</View>}
export function Button({title,onPress,busy=false,secondary=false}:{title:string;onPress:()=>void;busy?:boolean;secondary?:boolean}){return <Pressable onPress={onPress} disabled={busy} style={[s.button,secondary&&s.secondary]}>{busy?<ActivityIndicator color={secondary?c.accentBright:'#fff'}/>:<Text style={[s.buttonText,secondary&&s.secondaryText]}>{title}</Text>}</Pressable>}
export function Field({label,value,onChangeText,placeholder,keyboardType}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} keyboardType={keyboardType} style={s.input}/></View>}
export function FeatureRow({title,text,onPress,badge}:{title:string;text?:string;onPress:()=>void;badge?:string}){return <Pressable onPress={onPress} style={({pressed})=>[s.row,pressed&&{opacity:.72}]}><View style={s.rowIcon}><Text style={s.rowIconText}>{title.slice(0,1)}</Text></View><View style={s.rowCopy}><Text style={s.rowTitle}>{title}</Text>{text?<Text style={s.rowText}>{text}</Text>:null}</View>{badge?<Text style={s.badge}>{badge}</Text>:<Text style={s.arrow}>›</Text>}</Pressable>}
export function Empty({text}:{text:string}){return <Card><Text style={s.emptyTitle}>{text}</Text><Text style={s.muted}>Start adding data and AthleteN will build this view automatically.</Text></Card>}
export const ui=s;
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:c.background},content:{padding:18,paddingBottom:70},wrap:{gap:14},header:{gap:8,paddingTop:5},headerRow:{flexDirection:'row',alignItems:'center',gap:12},back:{alignSelf:'flex-start',paddingVertical:3,paddingHorizontal:2},backText:{color:c.accentBright,fontSize:10,fontWeight:'900',letterSpacing:.7},eyebrow:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1.6},title:{color:c.text,fontSize:30,fontWeight:'900',marginTop:2},subtitle:{color:c.muted,fontSize:12,lineHeight:18},sectionWrap:{gap:7},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{color:c.muted,fontSize:9,fontWeight:'900',letterSpacing:1.5},card:{backgroundColor:c.surface,borderWidth:1,borderColor:c.borderStrong,borderRadius:20,padding:15,gap:10},accentCard:{backgroundColor:c.accentSoft,borderColor:c.accentDeep},button:{backgroundColor:c.accent,borderRadius:13,minHeight:45,alignItems:'center',justifyContent:'center',paddingHorizontal:16},secondary:{backgroundColor:'transparent',borderWidth:1,borderColor:c.borderStrong},buttonText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},secondaryText:{color:c.accentBright},field:{gap:5},label:{color:c.textSecondary,fontSize:8,fontWeight:'900',letterSpacing:.8},input:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,paddingHorizontal:12,paddingVertical:11,fontSize:13},row:{minHeight:68,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:17,padding:12},rowIcon:{width:40,height:40,borderRadius:13,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},rowIconText:{color:c.accentBright,fontSize:12,fontWeight:'900'},rowCopy:{flex:1},rowTitle:{color:c.text,fontSize:13,fontWeight:'900'},rowText:{color:c.muted,fontSize:10,lineHeight:15,marginTop:2},badge:{color:c.accentBright,fontSize:8,fontWeight:'900'},arrow:{color:c.muted,fontSize:25},emptyTitle:{color:c.text,fontSize:14,fontWeight:'800'},muted:{color:c.muted,fontSize:10,lineHeight:16}
});