import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
const c=Colors.dark;
type Badge={badge_key:string;badge_label:string;description:string;category:string;rarity:string;icon:string;is_system_badge:boolean};
type Award={id:string;user_id:string;badge_key:string;badge_label:string;awarded_at:string;permanent:boolean};
export default function AdminBadgesScreen(){
 const {profile}=useAuth();const allowed=['admin','super_admin','support_admin'].includes(String(profile?.role||''));const [badges,setBadges]=useState<Badge[]>([]);const [awards,setAwards]=useState<Award[]>([]);const [userId,setUserId]=useState('');const [badgeKey,setBadgeKey]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!allowed)return;const [b,a]=await Promise.all([supabase.from('badge_definitions').select('*').order('category').order('badge_label'),supabase.from('athlete_badges').select('id,user_id,badge_key,badge_label,awarded_at,permanent').order('awarded_at',{ascending:false}).limit(100)]);if(b.error||a.error)setMessage(b.error?.message||a.error?.message||'Could not load badge administration.');setBadges((b.data||[]) as Badge[]);setAwards((a.data||[]) as Award[])},[allowed]);useEffect(()=>{void load()},[load]);
 async function award(){if(!userId.trim()||!badgeKey)return;setBusy(true);const {error}=await supabase.rpc('admin_award_badge',{p_user_id:userId.trim(),p_badge_key:badgeKey,p_metadata:{source:'admin_panel'}});setBusy(false);if(error)setMessage(error.message);else{setMessage('Badge awarded.');setUserId('');await load()}}
 async function revoke(id:string,permanent:boolean){if(permanent){setMessage('Permanent system badges cannot be revoked.');return}Alert.alert('Revoke badge','This removes the earned badge.',[{text:'Cancel',style:'cancel'},{text:'Revoke',style:'destructive',onPress:async()=>{setBusy(true);const {error}=await supabase.rpc('admin_revoke_badge',{p_badge_id:id});setBusy(false);if(error)setMessage(error.message);else await load()}}])}
 if(!allowed)return <View style={s.denied}><Text style={s.title}>Admin access required</Text></View>;
 return <SafeAreaView style={s.screen} edges={['top']}><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>SUPER ADMIN</Text><Text style={s.title}>Badge Control</Text><Text style={s.sub}>Secure server-authorized awarding. System badges are permanent.</Text><View style={s.panel}><Text style={s.head}>AWARD BADGE</Text><TextInput value={userId} onChangeText={setUserId} placeholder="Athlete user UUID" placeholderTextColor={c.muted} style={s.input}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.picker}>{badges.map(b=><Pressable key={b.badge_key} onPress={()=>setBadgeKey(b.badge_key)} style={[s.choice,badgeKey===b.badge_key&&s.active]}><Text style={s.choiceIcon}>{b.icon}</Text><Text style={s.choiceText}>{b.badge_label}</Text></Pressable>)}</ScrollView><Pressable disabled={busy||!userId.trim()||!badgeKey} onPress={()=>void award()} style={s.primary}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>AWARD SECURELY</Text>}</Pressable></View><Text style={s.section}>RECENT AWARDS</Text>{awards.map(a=><View key={a.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{a.badge_label}</Text><Text style={s.meta}>{a.user_id} • {new Date(a.awarded_at).toLocaleString()}</Text></View><Pressable onPress={()=>void revoke(a.id,a.permanent)}><Text style={[s.revoke,a.permanent&&s.disabled]}>{a.permanent?'PERMANENT':'REVOKE'}</Text></Pressable></View>)}{message?<Text style={s.message}>{message}</Text>:null}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.background},content:{padding:18,paddingBottom:50,gap:12},kicker:{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:c.text,fontSize:30,fontWeight:'900',marginTop:5},sub:{color:c.muted,fontSize:11,lineHeight:17},panel:{backgroundColor:c.surface,borderWidth:1,borderColor:c.borderStrong,borderRadius:20,padding:15,gap:10},head:{color:c.text,fontSize:11,fontWeight:'900',letterSpacing:1},input:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:12,fontSize:12},picker:{gap:7},choice:{width:115,borderWidth:1,borderColor:c.border,borderRadius:13,padding:9,backgroundColor:c.background},active:{borderColor:c.accent,backgroundColor:c.accentSoft},choiceIcon:{fontSize:20},choiceText:{color:c.text,fontSize:9,fontWeight:'800',marginTop:5},primary:{backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'},primaryText:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},section:{color:c.muted,fontSize:9,fontWeight:'900',letterSpacing:1.5,marginTop:5},row:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:15,padding:12},name:{color:c.text,fontSize:12,fontWeight:'900'},meta:{color:c.muted,fontSize:9,lineHeight:14,marginTop:3},revoke:{color:c.danger,fontSize:8,fontWeight:'900'},disabled:{color:c.muted},message:{color:c.accentBright,fontSize:10},denied:{flex:1,backgroundColor:c.background,alignItems:'center',justifyContent:'center'}});
