import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,Text,TextInput,View,StyleSheet } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Colors } from '@/constants/theme';

const c=Colors.dark;
export default function AICoachScreen(){
 const {session,profile}=useAuth();const [busy,setBusy]=useState(false);const [training,setTraining]=useState(0);const [sessions,setSessions]=useState(0);const [upcoming,setUpcoming]=useState(0);const [goals,setGoals]=useState(0);const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');
 const load=useCallback(async()=>{if(!session)return;setBusy(true);const uid=session.user.id;const [t,e,g]=await Promise.all([supabase.from('training_sessions').select('minutes').eq('user_id',uid).gte('session_date',new Date(Date.now()-14*86400000).toISOString().slice(0,10)),supabase.from('tournaments').select('id',{count:'exact',head:true}).eq('user_id',uid).gte('starts_at',new Date().toISOString()),supabase.from('goals').select('progress,status').eq('user_id',uid)]);setTraining((t.data||[]).reduce((s,x)=>s+Number(x.minutes||0),0));setSessions((t.data||[]).length);setUpcoming(e.count||0);setGoals((g.data||[]).filter(x=>x.status!=='completed').length);setBusy(false)},[session]);useEffect(()=>{void load()},[load]);
 function ask(text:string){const q=text.toLowerCase();let a='';if(q.includes('train')||q.includes('workout'))a=training?`You have logged ${training} minutes across ${sessions} sessions in the last 14 days. Use your coach's planned workload and keep your next session focused on quality.`:'I do not have enough recent training data yet. Log your sessions and I can summarize your training pattern.';else if(q.includes('competition')||q.includes('tournament'))a=upcoming?`You have ${upcoming} upcoming competition event${upcoming===1?'':'s'} saved. Open Compete to review the event details and use the checklist before competition.`:'There is no upcoming competition saved yet. Add one in Compete so your preparation can be connected to it.';else if(q.includes('goal'))a=goals?`You currently have ${goals} active goal${goals===1?'':'s'}. Keep progress updated in Profile so AthleteN can visualize it.`:'You have no active goals recorded. Add one in Profile to give your training a clear direction.';else a=`I can currently help interpret your saved training, competition and goal signals. Try asking about training, competition or goals. Your ${profile?.discipline||'Taekwondo'} discipline is active.`;setAnswer(a);setQuestion('')}
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.kicker}>ATHLETEN AI COACH</Text><Text style={s.title}>Your training copilot.</Text><Text style={s.sub}>A coach-style layer over the real records in your AthleteN account.</Text>
 <View style={s.hero}><View><Text style={s.heroKicker}>{String(profile?.discipline||'TAEKWONDO').toUpperCase()} COACH</Text><Text style={s.heroTitle}>Ask about your athlete data.</Text><Text style={s.heroText}>No fake stats. Coach responses use the training, competition and goals saved to your account.</Text></View><Pressable onPress={()=>void load()} style={s.refresh}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.refreshText}>REFRESH</Text>}</Pressable></View>
 <View style={s.cards}><Metric label="14D TRAINING" value={training+' min'}/><Metric label="SESSIONS" value={String(sessions)}/><Metric label="UPCOMING" value={String(upcoming)}/></View>
 <Text style={s.section}>QUICK COACH QUESTIONS</Text><View style={s.quick}>{['How is my training?','What about my competition?','How are my goals?'].map(x=><Pressable key={x} onPress={()=>ask(x)} style={s.quickButton}><Text style={s.quickText}>{x}</Text></Pressable>)}</View>
 <View style={s.chat}><Text style={s.chatLabel}>ASK ATHLETEN COACH</Text><TextInput value={question} onChangeText={setQuestion} onSubmitEditing={()=>ask(question)} placeholder="Ask about training, competition or goals…" placeholderTextColor={c.muted} style={s.input}/><Pressable onPress={()=>ask(question)} style={s.ask}><Text style={s.askText}>ASK COACH</Text></Pressable>{answer?<View style={s.answer}><Text style={s.answerLabel}>COACH</Text><Text style={s.answerText}>{answer}</Text></View>:null}</View>
 
</ScrollView>
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.background},content:{padding:18,paddingBottom:50,gap:13},kicker:{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1.6},title:{color:c.text,fontSize:31,fontWeight:'900'},sub:{color:c.muted,fontSize:12,lineHeight:18},hero:{backgroundColor:c.accentSoft,borderWidth:1,borderColor:c.accentDeep,borderRadius:23,padding:17,gap:12},heroKicker:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1.3},heroTitle:{color:c.text,fontSize:20,fontWeight:'900'},heroText:{color:'#BBD6FF',fontSize:11,lineHeight:17},refresh:{backgroundColor:c.accent,borderRadius:12,height:42,alignItems:'center',justifyContent:'center'},refreshText:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},cards:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:15,padding:12},metricValue:{color:c.text,fontSize:17,fontWeight:'900'},metricLabel:{color:c.muted,fontSize:7,fontWeight:'900',letterSpacing:.8,marginTop:4},section:{color:c.text,fontSize:10,fontWeight:'900',letterSpacing:1.4},quick:{gap:8},quickButton:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:14,padding:13},quickText:{color:c.text,fontSize:11,fontWeight:'800'},chat:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:20,padding:15,gap:10},chatLabel:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1.2},input:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:12,fontSize:12},ask:{backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'},askText:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},answer:{backgroundColor:c.accentSoft,borderWidth:1,borderColor:c.accentDeep,borderRadius:14,padding:13,gap:5},answerLabel:{color:c.accentBright,fontSize:8,fontWeight:'900'},answerText:{color:c.text,fontSize:11,lineHeight:18}});
