// @ts-nocheck
import { useCallback,useEffect,useState } from 'react';
import { Pressable,ScrollView,Text,TextInput,View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';
const input={backgroundColor:c.panel,borderWidth:1,borderColor:c.border,borderRadius:10,padding:11,color:c.text,fontSize:11};
const btn={backgroundColor:c.accent,borderRadius:10,padding:11,alignItems:'center'};
function Field({label,value,onChangeText,placeholder,multi=false}){return <View style={{gap:5}}><Text style={{color:c.muted,fontSize:8,fontWeight:'900'}}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} multiline={multi} style={[input,multi&&{minHeight:70,textAlignVertical:'top'}]}/></View>}
function Add({title,children,onSave}){return <Card><Text style={{color:c.text,fontWeight:'900',fontSize:12,marginBottom:9}}>{title}</Text><View style={{gap:8}}>{children}<Pressable onPress={onSave} style={btn}><Text style={{color:'#fff',fontWeight:'900',fontSize:9}}>SAVE</Text></Pressable></View></Card>}
export default function AthleteJourney(){
 const {session}=useAuth(); const [message,setMessage]=useState(''); const [refresh,setRefresh]=useState(0);
 const [season,setSeason]=useState({name:'',start:'',end:'',goal:''}); const [journal,setJournal]=useState({title:'',result:'',worked:'',improve:'',coach:'',next:''});
 const [iq,setIq]=useState({style:'',used:'',worked:'',failed:'',lesson:'',coach:''}); const [tech,setTech]=useState({name:'',cat:'Kyorugi',level:'1',count:'0',note:''});
 const [challenge,setChallenge]=useState({title:'',target:'',unit:'',due:''}); const [record,setRecord]=useState({title:'',value:'',unit:'',date:'',notes:''});
 const [milestone,setMilestone]=useState({title:'',date:''}); const [timeline,setTimeline]=useState({title:'',date:'',desc:''});
 const [rows,setRows]=useState<any>({});
 const load=useCallback(async()=>{if(!session)return;const tables=['athlete_seasons','competition_journals','fight_iq_entries','technique_progress','athlete_challenges','personal_records','athlete_milestones','athlete_timeline_events'];const out:any={};for(const t of tables){const r=await supabase.from(t).select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(8);out[t]=r.data||[]}setRows(out)},[session,refresh]);
 useEffect(()=>{void load()},[load]);
 const save=async(table,data)=>{if(!session)return;setMessage('');const {error}=await supabase.from(table).insert({...data,user_id:session.user.id,created_by:table==='athlete_challenges'?session.user.id:undefined});if(error)setMessage(error.message);else{setMessage('Saved.');setRefresh(x=>x+1)}};
 const remove=async(table,id)=>{const {error}=await supabase.from(table).delete().eq('id',id).eq('user_id',session?.user.id);if(error)setMessage(error.message);else setRefresh(x=>x+1)};
 return <Screen><Header back eyebrow="ATHLETEN JOURNEY" title="Athlete Journey" subtitle="Season, competition review, Fight IQ, techniques, challenges, records and milestones."/><ScrollView contentContainerStyle={{paddingBottom:50}}>
 <Section title="SEASON MODE"><Add title="Create season" onSave={()=>save('athlete_seasons',{name:season.name,start_date:season.start,end_date:season.end||null,goal:season.goal})}><Field label="NAME" value={season.name} onChangeText={v=>setSeason({...season,name:v})} placeholder="2026–27 Competition Season"/><Field label="START DATE" value={season.start} onChangeText={v=>setSeason({...season,start:v})} placeholder="YYYY-MM-DD"/><Field label="END DATE" value={season.end} onChangeText={v=>setSeason({...season,end:v})} placeholder="Optional"/><Field label="MAIN GOAL" value={season.goal} onChangeText={v=>setSeason({...season,goal:v})} placeholder="Qualify for nationals"/></Add>{(rows.athlete_seasons||[]).map(x=><Card key={x.id}><Text style={{color:c.text,fontWeight:'900'}}>{x.name}</Text><Text style={{color:c.muted,fontSize:9}}>{x.start_date} → {x.end_date||'open'} · {x.goal||'No goal'}</Text></Card>)}</Section>
 <Section title="COMPETITION JOURNAL"><Add title="Post-competition review" onSave={()=>save('competition_journals',{title:journal.title,result:journal.result,what_worked:journal.worked,improve_next:journal.improve,coach_feedback:journal.coach,next_target:journal.next})}><Field label="EVENT" value={journal.title} onChangeText={v=>setJournal({...journal,title:v})} placeholder="Rajasthan Cup 2026"/><Field label="RESULT" value={journal.result} onChangeText={v=>setJournal({...journal,result:v})} placeholder="Result / round reached"/><Field label="WHAT WORKED" value={journal.worked} onChangeText={v=>setJournal({...journal,worked:v})} placeholder="What worked" multi/><Field label="IMPROVE NEXT" value={journal.improve} onChangeText={v=>setJournal({...journal,improve:v})} placeholder="What to improve" multi/><Field label="COACH FEEDBACK" value={journal.coach} onChangeText={v=>setJournal({...journal,coach:v})} placeholder="Coach feedback" multi/><Field label="NEXT TARGET" value={journal.next} onChangeText={v=>setJournal({...journal,next:v})} placeholder="Next objective"/></Add>{(rows.competition_journals||[]).map(x=><Card key={x.id}><Text style={{color:c.text,fontWeight:'900'}}>{x.title}</Text><Text style={{color:c.muted,fontSize:9}}>{x.result||'No result'} · Next: {x.next_target||'—'}</Text></Card>)}</Section>
 <Section title="FIGHT IQ"><Add title="Tactical entry" onSave={()=>save('fight_iq_entries',{opponent_style:iq.style,techniques_used:iq.used,what_worked:iq.worked,what_failed:iq.failed,tactical_lesson:iq.lesson,coach_notes:iq.coach})}><Field label="OPPONENT STYLE" value={iq.style} onChangeText={v=>setIq({...iq,style:v})} placeholder="Pressure / counter / tall"/><Field label="TECHNIQUES USED" value={iq.used} onChangeText={v=>setIq({...iq,used:v})} placeholder="Front-leg, cut kick"/><Field label="WORKED" value={iq.worked} onChangeText={v=>setIq({...iq,worked:v})} placeholder="What worked" multi/><Field label="FAILED" value={iq.failed} onChangeText={v=>setIq({...iq,failed:v})} placeholder="What failed" multi/><Field label="TACTICAL LESSON" value={iq.lesson} onChangeText={v=>setIq({...iq,lesson:v})} placeholder="Lesson to remember" multi/><Field label="COACH NOTES" value={iq.coach} onChangeText={v=>setIq({...iq,coach:v})} placeholder="Coach feedback" multi/></Add></Section>
 <Section title="TECHNIQUE PROGRESS"><Add title="Track a technique" onSave={()=>save('technique_progress',{technique:tech.name,category:tech.cat,level:Math.max(1,Math.min(5,Number(tech.level)||1)),practice_count:Math.max(0,Number(tech.count)||0),coach_note:tech.note})}><Field label="TECHNIQUE" value={tech.name} onChangeText={v=>setTech({...tech,name:v})} placeholder="Back kick"/><Field label="CATEGORY" value={tech.cat} onChangeText={v=>setTech({...tech,cat:v})} placeholder="Kyorugi"/><Field label="LEVEL 1–5" value={tech.level} onChangeText={v=>setTech({...tech,level:v})} placeholder="1"/><Field label="PRACTICE COUNT" value={tech.count} onChangeText={v=>setTech({...tech,count:v})} placeholder="100"/><Field label="COACH NOTE" value={tech.note} onChangeText={v=>setTech({...tech,note:v})} placeholder="Coach feedback" multi/></Add>{(rows.technique_progress||[]).map(x=><Card key={x.id}><Text style={{color:c.text,fontWeight:'900'}}>{x.technique}</Text><Text style={{color:c.muted,fontSize:9}}>Level {x.level}/5 · {x.practice_count} practices · {x.category}</Text></Card>)}</Section>
 <Section title="CHALLENGES"><Add title="Create a challenge" onSave={()=>save('athlete_challenges',{title:challenge.title,target_value:Number(challenge.target)||null,unit:challenge.unit||null,due_date:challenge.due||null})}><Field label="CHALLENGE" value={challenge.title} onChangeText={v=>setChallenge({...challenge,title:v})} placeholder="8 training sessions"/><Field label="TARGET" value={challenge.target} onChangeText={v=>setChallenge({...challenge,target:v})} placeholder="8"/><Field label="UNIT" value={challenge.unit} onChangeText={v=>setChallenge({...challenge,unit:v})} placeholder="sessions"/><Field label="DUE DATE" value={challenge.due} onChangeText={v=>setChallenge({...challenge,due:v})} placeholder="YYYY-MM-DD"/></Add></Section>
 <Section title="PERSONAL RECORDS"><Add title="Add a record" onSave={()=>save('personal_records',{title:record.title,value:record.value?Number(record.value):null,unit:record.unit||null,recorded_at:record.date||null,notes:record.notes||null})}><Field label="RECORD" value={record.title} onChangeText={v=>setRecord({...record,title:v})} placeholder="Fastest drill"/><Field label="VALUE" value={record.value} onChangeText={v=>setRecord({...record,value:v})} placeholder="12.4"/><Field label="UNIT" value={record.unit} onChangeText={v=>setRecord({...record,unit:v})} placeholder="seconds"/><Field label="DATE" value={record.date} onChangeText={v=>setRecord({...record,date:v})} placeholder="YYYY-MM-DD"/><Field label="NOTES" value={record.notes} onChangeText={v=>setRecord({...record,notes:v})} placeholder="Details" multi/></Add>{(rows.personal_records||[]).map(x=><Card key={x.id}><Text style={{color:c.text,fontWeight:'900'}}>{x.title}</Text><Text style={{color:c.muted,fontSize:9}}>{x.value??'—'} {x.unit||''}</Text></Card>)}</Section>
 <Section title="MILESTONES & TIMELINE"><Add title="Add milestone" onSave={()=>save('athlete_milestones',{title:milestone.title,achieved_at:milestone.date||null})}><Field label="MILESTONE" value={milestone.title} onChangeText={v=>setMilestone({...milestone,title:v})} placeholder="First district gold"/><Field label="DATE" value={milestone.date} onChangeText={v=>setMilestone({...milestone,date:v})} placeholder="YYYY-MM-DD"/></Add><Add title="Add timeline event" onSave={()=>save('athlete_timeline_events',{title:timeline.title,event_date:timeline.date||new Date().toISOString().slice(0,10),description:timeline.desc||null})}><Field label="EVENT" value={timeline.title} onChangeText={v=>setTimeline({...timeline,title:v})} placeholder="Started Kyorugi"/><Field label="DATE" value={timeline.date} onChangeText={v=>setTimeline({...timeline,date:v})} placeholder="YYYY-MM-DD"/><Field label="DESCRIPTION" value={timeline.desc} onChangeText={v=>setTimeline({...timeline,desc:v})} placeholder="What happened" multi/></Add>{(rows.athlete_timeline_events||[]).map(x=><Card key={x.id}><Text style={{color:c.text,fontWeight:'900'}}>{x.title}</Text><Text style={{color:c.muted,fontSize:9}}>{x.event_date} · {x.verification_status==='verified'?'✓ VERIFIED':'SELF-REPORTED'}</Text></Card>)}</Section>
 <Card><Text style={{color:c.accentBright,fontWeight:'900'}}>TRUST MODEL</Text><Text style={{color:c.muted,fontSize:10,lineHeight:16}}>Athletes can record their journey, but they cannot mark their own achievements as verified. Competition results, medals, certificates, milestones and timeline claims can be submitted for review. Only a linked coach or platform admin can approve them.</Text></Card>
 {message?<Text style={{color:c.danger,fontSize:10,margin:12}}>{message}</Text>:null}
 </ScrollView></Screen>
}
