import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors } from '@/constants/theme';
import { Icon } from '@/components/mobile-ui';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from 'expo-router';
import { supabase } from '@/lib/supabase';

const c = Colors.dark;
type Definition={badge_key:string;badge_label:string;description:string;category:string;rarity:string;icon:string};
type Earned=Definition&{id:string;awarded_at:string;permanent:boolean};

export default function BadgesScreen(){
 const {session}=useAuth(); const router=useRouter(); const [earned,setEarned]=useState<Earned[]>([]); const [catalog,setCatalog]=useState<Definition[]>([]); const [busy,setBusy]=useState(true); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!session)return;setBusy(true);const [e,d]=await Promise.all([supabase.from('athlete_badges').select('id,badge_key,badge_label,awarded_at,permanent').eq('user_id',session.user.id).order('awarded_at',{ascending:false}),supabase.from('badge_definitions').select('badge_key,badge_label,description,category,rarity,icon').order('category').order('badge_label')]);if(e.error||d.error)setMessage(e.error?.message||d.error?.message||'Could not load badges.');const defs=(d.data||[]) as Definition[];const map=new Map(defs.map(x=>[x.badge_key,x]));setCatalog(defs);setEarned(((e.data||[]) as any[]).map(x=>({...map.get(x.badge_key),...x})).filter(x=>x.badge_label) as Earned[]);setBusy(false)},[session]);
 useEffect(()=>{void load()},[load]);
 return <SafeAreaView style={s.screen} edges={['top']}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Icon name="arrow" size={17} color={c.text}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>ATHLETEN PROGRESSION</Text><Text style={s.title}>Badges</Text></View><View style={s.count}><Text style={s.countText}>{earned.length}</Text></View></View>
  <View style={s.hero}><Text style={s.heroTitle}>YOUR ATHLETEN JOURNEY</Text><Text style={s.heroText}>Achievements come from real athlete activity. System badges are protected and server-assigned.</Text></View>
  {message?<Text style={s.message}>{message}</Text>:null}
  {busy?<View style={s.loading}><ActivityIndicator color={c.accentBright}/><Text style={s.meta}>Loading badges...</Text></View>:earned.length?<View style={s.grid}>{earned.map(b=><View key={b.id} style={s.card}><View style={s.icon}><Text style={s.iconText}>{b.icon||'🏅'}</Text></View><View style={{flex:1}}><Text style={s.badgeName}>{b.badge_label}</Text><Text style={s.meta}>{b.description}</Text><View style={s.metaRow}><Text style={s.rarity}>{String(b.rarity).toUpperCase()}</Text><Text style={s.date}>{new Date(b.awarded_at).toLocaleDateString()}</Text></View></View></View>)}</View>:<View style={s.empty}><Text style={s.emptyTitle}>Your badge journey starts here.</Text><Text style={s.meta}>Training, competition and progress can unlock achievements.</Text></View>}
  <Text style={s.section}>BADGE CATALOG</Text><View style={s.catalog}>{catalog.map(b=>{const has=earned.some(x=>x.badge_key===b.badge_key);return <View key={b.badge_key} style={[s.catalogRow,has&&s.catalogEarned]}><Text style={s.catalogIcon}>{b.icon||'🏅'}</Text><View style={{flex:1}}><Text style={s.catalogName}>{b.badge_label}</Text><Text style={s.meta}>{b.description}</Text></View><Text style={has?s.earned:s.locked}>{has?'EARNED':'LOCKED'}</Text></View>})}</View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.background},content:{padding:18,paddingBottom:50,gap:13},header:{flexDirection:'row',alignItems:'center',gap:10},back:{width:42,height:42,borderRadius:14,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',transform:[{rotate:'180deg'}]},kicker:{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:c.text,fontSize:30,fontWeight:'900',marginTop:3},count:{minWidth:44,height:44,borderRadius:14,backgroundColor:c.accentSoft,borderWidth:1,borderColor:c.accent,alignItems:'center',justifyContent:'center'},countText:{color:c.accentBright,fontWeight:'900'},hero:{backgroundColor:c.surface,borderWidth:1,borderColor:c.borderStrong,borderRadius:22,padding:17},heroTitle:{color:c.text,fontSize:12,fontWeight:'900',letterSpacing:1},heroText:{color:c.muted,fontSize:11,lineHeight:17,marginTop:7},grid:{gap:9},card:{flexDirection:'row',gap:12,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:18,padding:13},icon:{width:48,height:48,borderRadius:15,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},iconText:{fontSize:25},badgeName:{color:c.text,fontSize:14,fontWeight:'900'},meta:{color:c.muted,fontSize:10,lineHeight:15,marginTop:3},metaRow:{flexDirection:'row',gap:10,marginTop:8,alignItems:'center'},rarity:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1},date:{color:c.muted,fontSize:8},message:{color:c.danger,fontSize:11},loading:{alignItems:'center',padding:30,gap:8},empty:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:18,padding:18},emptyTitle:{color:c.text,fontSize:14,fontWeight:'900'},section:{color:c.muted,fontSize:9,fontWeight:'900',letterSpacing:1.5,marginTop:6},catalog:{gap:7},catalogRow:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:15,padding:11},catalogEarned:{borderColor:c.accent},catalogIcon:{fontSize:20},catalogName:{color:c.text,fontSize:12,fontWeight:'800'},earned:{color:c.success,fontSize:8,fontWeight:'900'},locked:{color:c.muted,fontSize:8,fontWeight:'900'}});
