// @ts-nocheck
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Pressable,ScrollView,Text,TextInput,View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';
const types=['training','competition','recovery','medical','reminder','travel'];
const pad=(n)=>String(n).padStart(2,'0'); const keyOf=(d)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function Field({label,value,onChangeText,placeholder}){return <View style={{gap:4}}><Text style={{color:c.muted,fontSize:8,fontWeight:'900'}}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} style={{backgroundColor:c.panel,borderWidth:1,borderColor:c.border,borderRadius:10,padding:10,color:c.text,fontSize:11}}/></View>}
export default function CalendarScreen(){
 const {session}=useAuth(); const now=new Date(); const [month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1)); const [selected,setSelected]=useState(keyOf(now)); const [events,setEvents]=useState<any[]>([]); const [form,setForm]=useState({title:'',type:'training',time:'18:00',notes:''}); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!session)return;const start=new Date(month.getFullYear(),month.getMonth(),1);const end=new Date(month.getFullYear(),month.getMonth()+1,1);const [custom,training,comp]=await Promise.all([supabase.from('calendar_events').select('*').eq('user_id',session.user.id).gte('event_date',start.toISOString()).lt('event_date',end.toISOString()).order('event_date',{ascending:true}),supabase.from('training_sessions').select('id,title,session_date,minutes,intensity').eq('user_id',session.user.id).gte('session_date',keyOf(start)).lt('session_date',keyOf(end)),supabase.from('tournaments').select('id,name,starts_at,location,status').eq('user_id',session.user.id).gte('starts_at',start.toISOString()).lt('starts_at',end.toISOString())]);const rows=[...(custom.data||[]).map(x=>({...x,_kind:x.event_type,_date:x.event_date})),...(training.data||[]).map(x=>({...x,_kind:'training',_date:x.session_date,title:x.title||'Training session'})),...(comp.data||[]).map(x=>({...x,_kind:'competition',_date:x.starts_at,title:x.name,notes:x.location||''}))];setEvents(rows.sort((a,b)=>String(a._date).localeCompare(String(b._date))));if(custom.error)setMessage(custom.error.message)},[session,month]);
 useEffect(()=>{void load()},[load]);
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(first.getDay()+6)%7;return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]},[month]);
 const selectedEvents=events.filter(e=>keyOf(new Date(e._date))===selected);
 const add=async()=>{if(!session||!form.title.trim()){setMessage('Enter an event title.');return}const dt=new Date(`${selected}T${form.time||'09:00'}:00`);if(Number.isNaN(dt.getTime())){setMessage('Use a valid time such as 18:00.');return}const {error}=await supabase.from('calendar_events').insert({user_id:session.user.id,title:form.title.trim(),event_type:types.includes(form.type)?form.type:'reminder',event_date:dt.toISOString(),notes:form.notes||null});setMessage(error?error.message:'Event added.');if(!error){setForm({title:'',type:'training',time:'18:00',notes:''});await load()}};
 const remove=async(id)=>{const {error}=await supabase.from('calendar_events').delete().eq('id',id).eq('user_id',session?.user.id);setMessage(error?error.message:'Event deleted.');if(!error)await load()};
 return <Screen><Header eyebrow="ATHLETEN PLANNER" title="Calendar" subtitle="Training, competition, recovery, medical, reminders and travel in one real schedule."/><ScrollView contentContainerStyle={{paddingBottom:50}}>
 <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><Text style={{color:c.accentBright,fontSize:22}}>‹</Text></Pressable><Text style={{color:c.text,fontSize:16,fontWeight:'900'}}>{month.toLocaleString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><Text style={{color:c.accentBright,fontSize:22}}>›</Text></Pressable></View>
 <Card><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['M','T','W','T','F','S','S'].map((x,i)=><Text key={i} style={{width:'14.28%',textAlign:'center',color:c.muted,fontSize:8,fontWeight:'900',marginBottom:7}}>{x}</Text>)}{days.map((d,i)=>d?<Pressable key={keyOf(d)} onPress={()=>setSelected(keyOf(d))} style={{width:'14.28%',height:45,alignItems:'center',justifyContent:'center'}}><View style={{width:31,height:31,borderRadius:16,backgroundColor:keyOf(d)===selected?c.accentSoft:'transparent',alignItems:'center',justifyContent:'center'}}><Text style={{color:keyOf(d)===selected?c.accentBright:c.text,fontWeight:'800',fontSize:10}}>{d.getDate()}</Text>{events.some(e=>keyOf(new Date(e._date))===keyOf(d))?<View style={{position:'absolute',bottom:1,width:4,height:4,borderRadius:2,backgroundColor:c.accentBright}}/>:null}</View></Pressable>:<View key={i} style={{width:'14.28%',height:45}}/>)}</View></Card>
 <Section title={`SCHEDULE · ${selected}`}>{selectedEvents.length?selectedEvents.map(e=><Card key={e.id||`${e._kind}-${e._date}`}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{flex:1}}><Text style={{color:c.text,fontWeight:'900',fontSize:12}}>{e.title}</Text><Text style={{color:c.muted,fontSize:9}}>{String(e._kind).toUpperCase()} · {new Date(e._date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text>{e.notes?<Text style={{color:c.muted,fontSize:9,marginTop:4}}>{e.notes}</Text>:null}</View>{e.id&&e.event_type?<Pressable onPress={()=>void remove(e.id)}><Text style={{color:c.danger,fontSize:9,fontWeight:'900'}}>DELETE</Text></Pressable>:null}</View></Card>):<Text style={{color:c.muted,fontSize:10}}>Nothing scheduled for this day.</Text>}</Section>
 <Section title="ADD EVENT"><Card><View style={{gap:9}}><Field label="TITLE" value={form.title} onChangeText={v=>setForm({...form,title:v})} placeholder="Academy training"/><Field label="TYPE" value={form.type} onChangeText={v=>setForm({...form,type:v})} placeholder="training / competition / recovery / medical / reminder / travel"/><Field label="TIME" value={form.time} onChangeText={v=>setForm({...form,time:v})} placeholder="18:00"/><Field label="NOTES" value={form.notes} onChangeText={v=>setForm({...form,notes:v})} placeholder="Optional notes"/><Pressable onPress={()=>void add()} style={{backgroundColor:c.accent,borderRadius:10,padding:12,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'900',fontSize:9}}>ADD TO CALENDAR</Text></Pressable></View></Card></Section>
 {message?<Text style={{color:c.accentBright,fontSize:10}}>{message}</Text>:null}
 </ScrollView></Screen>
}