import { useEffect,useState } from 'react';
import { Alert,Pressable,Text,TextInput,View } from 'react-native';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
export default function CoachTournaments(){const {profile}=useAuth();const [athletes,setAthletes]=useState<any[]>([]);const [items,setItems]=useState<any[]>([]);const [athlete,setAthlete]=useState('');const [name,setName]=useState('');const [date,setDate]=useState('');const [location,setLocation]=useState('');const [discipline,setDiscipline]=useState('Kyorugi');const [status,setStatus]=useState('planned');const [result,setResult]=useState('');const [busy,setBusy]=useState(false);const [athleteCode,setAthleteCode]=useState('');const [connectBusy,setConnectBusy]=useState(false);const [message,setMessage]=useState('');
async function load(){if(!profile?.user_id)return;const l=await supabase.from('coach_athlete_links').select('athlete_user_id').eq('coach_user_id',profile.user_id).eq('status','active');const ids=(l.data||[]).map((x:any)=>x.athlete_user_id);if(!ids.length){setAthletes([]);setItems([]);return}const p=await supabase.from('profiles').select('user_id,full_name,discipline').in('user_id',ids);setAthletes(p.data||[]);if(!athlete)setAthlete(ids[0]);const t=await supabase.from('tournaments').select('*').eq('coach_user_id',profile.user_id).order('starts_at',{ascending:true});setItems(t.data||[])}
useEffect(()=>{void load()},[profile?.user_id]);
async function addAthlete(){setConnectBusy(true);setMessage('');const {data,error}=await supabase.rpc('coach_add_athlete_by_account_code',{p_code:athleteCode.trim()});setConnectBusy(false);if(error){setMessage(error.message);return}setAthleteCode('');setMessage(`${data?.full_name||'Athlete'} connected.`);await load();}
async function add(){if(!profile?.user_id||!athlete||!name.trim())return;setBusy(true);const {error}=await supabase.from('tournaments').insert({user_id:athlete,coach_user_id:profile.user_id,name:name.trim(),starts_at:date.trim()||null,location:location.trim()||null,status,discipline,result:result.trim()||null,sport:'Taekwondo'});setBusy(false);if(error)Alert.alert('Could not save tournament',error.message);else{setName('');setDate('');setLocation('');setResult('');await load()}}
async function remove(id:string){const {error}=await supabase.from('tournaments').delete().eq('id',id);if(error)Alert.alert('Could not delete',error.message);else await load()}
return <Screen><Header back eyebrow="COACH / COMPETITION" title="Tournament Manager" subtitle="Create and manage tournaments for your connected athletes."/><Section title="ATHLETE"><Card><View style={{flexDirection:'row',gap:8,alignItems:'center'}}><TextInput value={athleteCode} onChangeText={setAthleteCode} placeholder="Add athlete by account code" placeholderTextColor={c.muted} autoCapitalize="characters" style={[i,{flex:1}]}/><Pressable disabled={connectBusy} onPress={()=>void addAthlete()} style={b}><Text style={{color:'#fff',fontWeight:'900',fontSize:9}}>{connectBusy?'…':'ADD'}</Text></Pressable></View>{message?<Text style={{color:c.accentBright,fontSize:10,marginBottom:8}}>{message}</Text>:null}{athletes.map(a=><Pressable key={a.user_id} onPress={()=>setAthlete(a.user_id)} style={{padding:11,borderWidth:1,borderColor:athlete===a.user_id?c.accent:c.border,borderRadius:11,marginBottom:7}}><Text style={{color:c.text,fontWeight:'900'}}>{a.full_name||'Athlete'}</Text><Text style={{color:c.muted,fontSize:9}}>{a.discipline||'Taekwondo'}</Text></Pressable>)}{!athletes.length?<Text style={{color:c.muted}}>Connect athletes first.</Text>:null}</Card></Section>
<Section title="ADD TOURNAMENT"><Card><TextInput value={name} onChangeText={setName} placeholder="Tournament name" placeholderTextColor={c.muted} style={i}/><TextInput value={date} onChangeText={setDate} placeholder="Date YYYY-MM-DD" placeholderTextColor={c.muted} style={i}/><TextInput value={location} onChangeText={setLocation} placeholder="Location" placeholderTextColor={c.muted} style={i}/><TextInput value={discipline} onChangeText={setDiscipline} placeholder="Kyorugi / Poomsae" placeholderTextColor={c.muted} style={i}/><TextInput value={status} onChangeText={setStatus} placeholder="planned / completed" placeholderTextColor={c.muted} style={i}/><TextInput value={result} onChangeText={setResult} placeholder="Result / notes" placeholderTextColor={c.muted} style={i}/><Pressable onPress={()=>void add()} disabled={busy} style={b}><Text style={{color:'#fff',fontWeight:'900',textAlign:'center'}}>SAVE TOURNAMENT</Text></Pressable></Card></Section>
<Section title="MANAGED TOURNAMENTS">{items.length?items.map(t=><Card key={t.id}><View style={{flexDirection:'row',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={{color:c.text,fontWeight:'900'}}>{t.name}</Text><Text style={{color:c.accentBright,fontSize:10}}>{athletes.find(a=>a.user_id===t.user_id)?.full_name||'Athlete'} · {t.starts_at||'Date not set'}</Text><Text style={{color:c.muted,fontSize:9}}>{t.location||'Location not set'} · {t.status||'planned'} · {t.result||'No result'}</Text></View><Pressable onPress={()=>void remove(t.id)}><Text style={{color:c.danger,fontSize:9,fontWeight:'900'}}>DELETE</Text></Pressable></View></Card>):<Card><Text style={{color:c.muted}}>No tournaments created by this Coach yet.</Text></Card>}</Section>
</Screen>}
const i={backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:12,fontSize:12,marginBottom:8} as any;const b={backgroundColor:c.accent,borderRadius:12,padding:13} as any;