import { useEffect, useMemo, useState } from 'react';
import { Text, View, Pressable } from 'react-native';
import { Screen, Header, Section, Card, c } from '@/components/mobile-ui';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
type Athlete={athlete_user_id:string;full_name?:string|null;discipline?:string|null};
export default function CoachCompetition(){
 const {profile}=useAuth();const [athletes,setAthletes]=useState<Athlete[]>([]);const [tournaments,setTournaments]=useState<any[]>([]);const [matches,setMatches]=useState<any[]>([]);const [medals,setMedals]=useState<any[]>([]);const [selected,setSelected]=useState('');
 const load=async()=>{if(!profile?.user_id)return;const l=await supabase.from('coach_athlete_links').select('athlete_user_id').eq('coach_user_id',profile.user_id).eq('status','active');const ids=(l.data||[]).map((x:any)=>x.athlete_user_id);if(!ids.length)return;const p=await supabase.from('profiles').select('user_id,full_name,discipline').in('user_id',ids);setAthletes((p.data||[]) as Athlete[]);const [t,m,md]=await Promise.all([supabase.from('tournaments').select('id,user_id,name,starts_at,location,status,result,discipline').in('user_id',ids).order('starts_at',{ascending:true}).limit(50),supabase.from('matches').select('id,user_id,tournament_id,opponent_name,division,round_name,result,score').in('user_id',ids).order('created_at',{ascending:false}).limit(100),supabase.from('medals').select('id,user_id,event_name,medal_type,category,awarded_at').in('user_id',ids).order('awarded_at',{ascending:false}).limit(100)]);setTournaments(t.data||[]);setMatches(m.data||[]);setMedals(md.data||[]);if(!selected)setSelected(ids[0]||'')};
useEffect(()=>{void load()},[profile?.user_id]);
const wins=matches.filter(m=>String(m.result||'').toLowerCase().includes('win')).length;const losses=matches.filter(m=>String(m.result||'').toLowerCase().includes('loss')).length;const upcoming=tournaments.filter(t=>t.starts_at&&new Date(t.starts_at)>=new Date(new Date().toISOString().slice(0,10))).length;
const mine=(x:any)=>!selected||x.user_id===selected;const athleteName=(id:string)=>athletes.find(a=>a.athlete_user_id===id)?.full_name||'Athlete';
return <Screen><Header eyebrow="COACH / COMPETITION" title="Competition Center" subtitle="See tournament schedules, match records and medals across your connected roster."/>
<Section title="COMPETITION SNAPSHOT"><View style={{flexDirection:'row',gap:8}}><Card><Text style={{color:c.accentBright,fontSize:22,fontWeight:'900'}}>{upcoming}</Text><Text style={{color:c.muted,fontSize:9}}>Upcoming</Text></Card><Card><Text style={{color:c.text,fontSize:22,fontWeight:'900'}}>{wins}</Text><Text style={{color:c.muted,fontSize:9}}>Wins</Text></Card><Card><Text style={{color:c.text,fontSize:22,fontWeight:'900'}}>{losses}</Text><Text style={{color:c.muted,fontSize:9}}>Losses</Text></Card><Card><Text style={{color:c.text,fontSize:22,fontWeight:'900'}}>{medals.length}</Text><Text style={{color:c.muted,fontSize:9}}>Medals</Text></Card></View></Section>
<Section title="ATHLETE FILTER"><Card>{athletes.map(a=><Pressable key={a.athlete_user_id} onPress={()=>setSelected(a.athlete_user_id)} style={{padding:11,borderBottomWidth:1,borderBottomColor:c.border}}><Text style={{color:selected===a.athlete_user_id?c.accentBright:c.text,fontWeight:'900'}}>{a.full_name||'Athlete'}</Text><Text style={{color:c.muted,fontSize:9}}>{a.discipline||'Taekwondo'}</Text></Pressable>)}</Card></Section>
<Section title="UPCOMING TOURNAMENTS">{tournaments.filter(t=>!t.starts_at||new Date(t.starts_at)>=new Date(new Date().toISOString().slice(0,10))).filter(mine).map(t=><Card key={t.id}><Text style={{color:c.text,fontWeight:'900'}}>{t.name}</Text><Text style={{color:c.accentBright,fontSize:10}}>{athleteName(t.user_id)} · {t.starts_at||'Date not set'}</Text><Text style={{color:c.muted,fontSize:10}}>{t.location||'Location not set'} · {t.status||'planned'}</Text></Card>)}{!tournaments.filter(t=>!t.starts_at||new Date(t.starts_at)>=new Date(new Date().toISOString().slice(0,10))).filter(mine).length?<Card><Text style={{color:c.muted}}>No upcoming tournaments for this athlete.</Text></Card>:null}</Section>
<Section title="MATCH HISTORY">{matches.filter(mine).slice(0,30).map(m=><Card key={m.id}><View style={{flexDirection:'row',justifyContent:'space-between'}}><View style={{flex:1}}><Text style={{color:c.text,fontWeight:'900'}}>{athleteName(m.user_id)} vs {m.opponent_name||'Opponent'}</Text><Text style={{color:c.muted,fontSize:9}}>{m.division||'Division'} · {m.round_name||'Round'}</Text></View><Text style={{color:c.accentBright,fontWeight:'900'}}>{m.result||'—'}</Text></View>{m.score?<Text style={{color:c.muted,fontSize:9}}>Score: {m.score}</Text>:null}</Card>)}</Section>
<Section title="MEDALS">{medals.filter(mine).slice(0,30).map(m=><Card key={m.id}><Text style={{color:c.accentBright,fontWeight:'900'}}>{m.medal_type.toUpperCase()}</Text><Text style={{color:c.text,fontWeight:'900'}}>{m.event_name}</Text><Text style={{color:c.muted,fontSize:9}}>{athleteName(m.user_id)} · {m.category||'Category not set'} · {m.awarded_at||'Date not set'}</Text></Card>)}</Section>
</Screen>;
}