import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, Text, TextInput, View } from 'react-native';
import { Screen, Header, Section, Card, Button, Field, c } from '@/components/mobile-ui';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

type Athlete={athlete_user_id:string;full_name?:string|null;discipline?:string|null;belt?:string|null;weight_kg?:number|null};
export default function CoachTraining(){
 const {profile}=useAuth(); const [athletes,setAthletes]=useState<Athlete[]>([]); const [selected,setSelected]=useState<string>(''); const [plans,setPlans]=useState<any[]>([]); const [sessions,setSessions]=useState<any[]>([]);
 const [title,setTitle]=useState('Competition Preparation'); const [focus,setFocus]=useState('Kyorugi'); const [days,setDays]=useState('30'); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{if(!profile?.user_id)return; const links=await supabase.from('coach_athlete_links').select('athlete_user_id').eq('coach_user_id',profile.user_id).eq('status','active'); const ids=(links.data||[]).map((x:any)=>x.athlete_user_id); if(!ids.length){setAthletes([]);setPlans([]);setSessions([]);return;}
 const p=await supabase.from('profiles').select('user_id,full_name,discipline,belt,weight_kg').in('user_id',ids); const a=(p.data||[]) as Athlete[]; setAthletes(a); if(!selected)setSelected(a[0]?.athlete_user_id||'');
 const pl=await supabase.from('training_plans').select('id,user_id,title,focus_area,starts_at,ends_at,status,notes,created_at').in('user_id',ids).eq('coach_user_id',profile.user_id).order('created_at',{ascending:false}).limit(40); setPlans(pl.data||[]);
 const ts=await supabase.from('training_sessions').select('id,user_id,title,session_date,minutes,intensity,notes,discipline').in('user_id',ids).order('session_date',{ascending:false}).limit(50); setSessions(ts.data||[]);
 };
 useEffect(()=>{void load()},[profile?.user_id]);
 const selectedName=athletes.find(a=>a.athlete_user_id===selected)?.full_name||'Select athlete';
 const totalMinutes=useMemo(()=>sessions.reduce((n,s)=>n+Number(s.minutes||0),0),[sessions]);
 async function createPlan(){const n=Number(days);if(!profile?.user_id||!selected||!title.trim()||!Number.isInteger(n)||n<1||n>365)return;setBusy(true);const start=new Date();const end=new Date(start);end.setDate(start.getDate()+n-1);const {error}=await supabase.from('training_plans').insert({user_id:selected,coach_user_id:profile.user_id,title:title.trim(),focus_area:focus.trim()||null,starts_at:start.toISOString().slice(0,10),ends_at:end.toISOString().slice(0,10),status:'active',notes:notes.trim()||null});setBusy(false);if(error)Alert.alert('Could not create plan',error.message);else{setNotes('');await load();}}
 return <Screen><Header eyebrow="COACH / TRAINING" title="Training Control" subtitle="Create managed plans and review the real training history of connected athletes."/>
 <Section title="ATHLETE"><Card>{athletes.length?<View style={{gap:8}}>{athletes.map(a=><Pressable key={a.athlete_user_id} onPress={()=>setSelected(a.athlete_user_id)} style={{padding:12,borderRadius:12,borderWidth:1,borderColor:selected===a.athlete_user_id?c.accent:c.border,backgroundColor:selected===a.athlete_user_id?c.accentSoft:c.background}}><Text style={{color:c.text,fontWeight:'900'}}>{a.full_name||'Athlete'}</Text><Text style={{color:c.muted,fontSize:10}}>{a.discipline||'Taekwondo'} · {a.belt||'Belt not set'} · {a.weight_kg??'—'} kg</Text></Pressable>)}</View>:<Text style={{color:c.muted}}>Connect an athlete first.</Text>}</Card></Section>
 <Section title="CREATE TRAINING PLAN"><Card><Text style={{color:c.accentBright,fontWeight:'900',fontSize:12}}>{selectedName}</Text><Field label="PLAN TITLE" value={title} onChangeText={setTitle} placeholder="Competition Preparation"/><Field label="FOCUS" value={focus} onChangeText={setFocus} placeholder="Kyorugi"/><Field label="DURATION (DAYS)" value={days} onChangeText={setDays} placeholder="30" keyboardType="number-pad"/><Field label="NOTES" value={notes} onChangeText={setNotes} placeholder="Coach instructions"/><Button title="CREATE MANAGED PLAN" onPress={()=>void createPlan()} busy={busy}/></Card></Section>
 <Section title="TEAM WORKLOAD"><Card><Text style={{color:c.text,fontSize:22,fontWeight:'900'}}>{totalMinutes} min</Text><Text style={{color:c.muted,fontSize:10}}>Visible logged training across connected athletes</Text></Card></Section>
 <Section title="ACTIVE & RECENT PLANS">{plans.length?plans.map(p=><Card key={p.id}><Text style={{color:c.text,fontWeight:'900'}}>{p.title}</Text><Text style={{color:c.muted,fontSize:10}}>{athletes.find(a=>a.athlete_user_id===p.user_id)?.full_name||'Athlete'} · {p.focus_area||'General'} · {p.status}</Text><Text style={{color:c.muted,fontSize:9}}>{p.starts_at||'—'} → {p.ends_at||'—'}</Text></Card>):<Card><Text style={{color:c.muted}}>No managed plans yet.</Text></Card>}</Section>
 <Section title="RECENT TRAINING">{sessions.length?sessions.slice(0,20).map(s=><Card key={s.id}><View style={{flexDirection:'row',justifyContent:'space-between'}}><View style={{flex:1}}><Text style={{color:c.text,fontWeight:'900'}}>{s.title}</Text><Text style={{color:c.muted,fontSize:10}}>{athletes.find(a=>a.athlete_user_id===s.user_id)?.full_name||'Athlete'} · {s.session_date}</Text></View><Text style={{color:c.accentBright,fontWeight:'900'}}>{s.minutes}m</Text></View>{s.notes?<Text style={{color:c.muted,fontSize:9}}>{s.notes}</Text>:null}</Card>):<Card><Text style={{color:c.muted}}>No training records yet.</Text></Card>}</Section>
 </Screen>
}