import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { PerformanceBars } from '@/components/performance-chart';

const c = Colors.dark;

export default function CompeteScreen() {
 const { session, profile } = useAuth();
 const [tournaments,setTournaments]=useState<any[]>([]); const [selected,setSelected]=useState<string|null>(null); const [matches,setMatches]=useState<any[]>([]); const [medals,setMedals]=useState<any[]>([]); const [checklist,setChecklist]=useState<any[]>([]);
 const [name,setName]=useState(''); const [date,setDate]=useState(''); const [location,setLocation]=useState('');
 const [opponent,setOpponent]=useState(''); const [round,setRound]=useState(''); const [result,setResult]=useState(''); const [score,setScore]=useState('');
 const [medalEvent,setMedalEvent]=useState(''); const [medalType,setMedalType]=useState(''); const [medalDate,setMedalDate]=useState(''); const [item,setItem]=useState('');
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const medalChart=[{label:'Gold',value:medals.filter(m=>String(m.medal_type).toLowerCase().includes('gold')).length},{label:'Silver',value:medals.filter(m=>String(m.medal_type).toLowerCase().includes('silver')).length},{label:'Bronze',value:medals.filter(m=>String(m.medal_type).toLowerCase().includes('bronze')).length}];

 const load=useCallback(async()=>{if(!session)return;const uid=session.user.id;const [t,m,cx]=await Promise.all([
  supabase.from('tournaments').select('id,name,starts_at,location,status,result').eq('user_id',uid).order('starts_at',{ascending:false}),
  supabase.from('medals').select('id,event_name,medal_type,category,awarded_at,result_notes').eq('user_id',uid).order('awarded_at',{ascending:false}),
  supabase.from('competition_checklists').select('id,item,category,completed').eq('user_id',uid).order('created_at',{ascending:false})
 ]);setTournaments(t.data||[]);setMedals(m.data||[]);setChecklist(cx.data||[]);if(selected){const r=await supabase.from('matches').select('id,opponent_name,division,round_name,result,score,notes').eq('user_id',uid).eq('tournament_id',selected).order('created_at',{ascending:false});setMatches(r.data||[])}},[session,selected]);
 useEffect(()=>{void load()},[load]);

 async function addTournament(){if(!session||!name.trim()){setMessage('Tournament name is required.');return}setBusy(true);const {data,error}=await supabase.from('tournaments').insert({user_id:session.user.id,name:name.trim(),starts_at:date.trim()||null,location:location.trim()||null,status:'planned'}).select().single();setBusy(false);if(error)setMessage(error.message);else{setName('');setDate('');setLocation('');setSelected(data.id);setMessage('Tournament saved.');await load()}}
 async function addMatch(){if(!session||!selected||!opponent.trim()){setMessage('Select a tournament and enter the opponent.');return}setBusy(true);const {error}=await supabase.from('matches').insert({user_id:session.user.id,tournament_id:selected,opponent_name:opponent.trim(),round_name:round.trim()||null,result:result.trim()||null,score:score.trim()||null});setBusy(false);if(error)setMessage(error.message);else{setOpponent('');setRound('');setResult('');setScore('');setMessage('Match saved.');await load()}}
 async function addMedal(){if(!session||!medalEvent.trim()||!medalType.trim()){setMessage('Event and medal type are required.');return}setBusy(true);const {error}=await supabase.from('medals').insert({user_id:session.user.id,event_name:medalEvent.trim(),medal_type:medalType.trim(),awarded_at:medalDate.trim()||null,category:profile?.discipline||null});setBusy(false);if(error)setMessage(error.message);else{setMedalEvent('');setMedalType('');setMedalDate('');setMessage('Medal saved.');await load()}}
 async function addChecklist(){if(!session||!item.trim()){setMessage('Checklist item is required.');return}setBusy(true);const {error}=await supabase.from('competition_checklists').insert({user_id:session.user.id,item:item.trim(),category:'equipment',completed:false});setBusy(false);if(error)setMessage(error.message);else{setItem('');await load()}}
 async function toggleCheck(x:any){const {error}=await supabase.from('competition_checklists').update({completed:!x.completed}).eq('id',x.id).eq('user_id',session?.user.id);if(error)setMessage(error.message);else await load()}
 async function remove(table:string,id:string){setBusy(true);const {error}=await supabase.from(table).delete().eq('id',id).eq('user_id',session?.user.id);setBusy(false);if(error)setMessage(error.message);else await load()}

 return <ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View><Text style={s.kicker}>ATHLETEN PERFORMANCE</Text><Text style={s.title}>Compete</Text><Text style={s.sub}>Events, matches, medals and your competition checklist.</Text></View>
  <View style={s.summary}><View><Text style={s.summaryKicker}>ATHLETE</Text><Text style={s.summaryTitle}>{profile?.discipline||'Taekwondo'} competitor</Text></View><Text style={s.trophy}>🏆</Text></View>
  <Section title="ADD TOURNAMENT"><Field label="TOURNAMENT NAME *" value={name} onChangeText={setName} placeholder="State / National Championship"/><View style={s.row}><View style={s.half}><Field label="DATE" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/></View><View style={s.half}><Field label="LOCATION" value={location} onChangeText={setLocation} placeholder="Venue"/></View></View><Button title="SAVE TOURNAMENT" onPress={addTournament} busy={busy}/></Section>
  <SectionHeader title="TOURNAMENTS" count={tournaments.length}/>
  <PerformanceBars title="Medal record" subtitle="Saved competition results" data={medalChart} unit="" accent={c.accentBright}/>
  {!tournaments.length?<Empty text="No tournaments saved yet."/>:tournaments.map(t=><Pressable key={t.id} onPress={()=>setSelected(t.id)} style={[s.event,t.id===selected&&s.eventActive]}><View style={s.eventTop}><View style={s.eventIcon}><Text style={s.eventIconText}>C</Text></View><View style={s.eventCopy}><Text style={s.eventTitle}>{t.name}</Text><Text style={s.meta}>{t.starts_at||'Date not set'}{t.location?' • '+t.location:''}</Text></View><Text style={s.chevron}>›</Text></View><Text style={s.status}>{(t.status||'planned').toUpperCase()}</Text></Pressable>)}
  {selected&&<Section title="MATCHES"><Field label="OPPONENT *" value={opponent} onChangeText={setOpponent} placeholder="Opponent name"/><View style={s.row}><View style={s.half}><Field label="ROUND" value={round} onChangeText={setRound} placeholder="Final"/></View><View style={s.half}><Field label="SCORE" value={score} onChangeText={setScore} placeholder="12-8"/></View></View><Field label="RESULT" value={result} onChangeText={setResult} placeholder="Win / Loss / Pending"/><Button title="SAVE MATCH" onPress={addMatch} busy={busy}/>{matches.map(m=><View style={s.inner} key={m.id}><View style={s.eventTop}><Text style={s.eventTitle}>{m.opponent_name}</Text><Text style={s.link}>{m.result||'Pending'}</Text></View><Text style={s.meta}>{m.round_name||'Round not set'}{m.score?' • '+m.score:''}</Text><Pressable onPress={()=>remove('matches',m.id)}><Text style={s.delete}>DELETE</Text></Pressable></View>)}{!matches.length&&<Text style={s.meta}>No matches recorded for this tournament.</Text>}</Section>}
  <Section title="MEDALS"><Field label="EVENT *" value={medalEvent} onChangeText={setMedalEvent} placeholder="Event name"/><Field label="MEDAL TYPE *" value={medalType} onChangeText={setMedalType} placeholder="Gold / Silver / Bronze"/><Field label="AWARDED DATE" value={medalDate} onChangeText={setMedalDate} placeholder="YYYY-MM-DD"/><Button title="SAVE MEDAL" onPress={addMedal} busy={busy}/>{medals.map(m=><View style={s.inner} key={m.id}><View style={s.eventTop}><Text style={s.eventTitle}>{m.event_name}</Text><Text style={s.link}>{m.medal_type}</Text></View><Text style={s.meta}>{m.awarded_at||'Date not set'}{m.category?' • '+m.category:''}</Text><Pressable onPress={()=>remove('medals',m.id)}><Text style={s.delete}>DELETE</Text></Pressable></View>)}</Section>
  <Section title="COMPETITION CHECKLIST"><Field label="NEW ITEM *" value={item} onChangeText={setItem} placeholder="Passport / dobok / protector"/><Button title="ADD CHECKLIST ITEM" onPress={addChecklist} busy={busy}/>{checklist.map(x=><View style={s.checkRow} key={x.id}><Pressable onPress={()=>toggleCheck(x)} style={[s.check,x.completed&&s.checkDone]}><Text style={s.checkText}>{x.completed?'✓':''}</Text></Pressable><Text style={[s.checkLabel,x.completed&&s.done]}>{x.item}</Text><Pressable onPress={()=>remove('competition_checklists',x.id)}><Text style={s.delete}>×</Text></Pressable></View>)}</Section>
  {message?<Text style={s.message}>{message}</Text>:null}
 </ScrollView>
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.sectionBlock}><Text style={s.section}>{title}</Text><View style={s.card}>{children}</View></View>}
function SectionHeader({title,count}:{title:string;count:number}){return <View style={s.sectionHead}><Text style={s.section}>{title}</Text><Text style={s.count}>{count}</Text></View>}
function Field({label,value,onChangeText,placeholder}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} style={s.input}/></View>}
function Button({title,onPress,busy}:{title:string;onPress:()=>void;busy:boolean}){return <Pressable onPress={onPress} disabled={busy} style={s.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{title}</Text>}</Pressable>}
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.emptyTitle}>{text}</Text></View>}
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:c.background},content:{paddingHorizontal:18,paddingTop:10,paddingBottom:45,gap:12},kicker:{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:c.text,fontSize:30,fontWeight:'900',marginTop:3},sub:{color:c.muted,fontSize:12,lineHeight:18},summary:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:c.accentSoft,borderWidth:1,borderColor:c.accentDeep,borderRadius:19,padding:16},summaryKicker:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1.2},summaryTitle:{color:c.text,fontSize:15,fontWeight:'900',marginTop:3},trophy:{fontSize:28},sectionBlock:{gap:7},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5},section:{color:c.muted,fontSize:9,fontWeight:'900',letterSpacing:1.5},count:{color:c.accentBright,fontSize:9,fontWeight:'900'},card:{backgroundColor:c.surfaceRaised,borderWidth:1,borderColor:c.border,borderRadius:19,padding:15,gap:10},field:{gap:5},row:{flexDirection:'row',gap:9},half:{flex:1},label:{color:c.textSecondary,fontSize:9,fontWeight:'900',letterSpacing:.7},input:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:11,fontSize:13},button:{backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'},buttonText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},event:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:17,padding:14,gap:8},eventActive:{borderColor:c.accent,backgroundColor:c.accentSoft},eventTop:{flexDirection:'row',alignItems:'center',gap:10},eventIcon:{width:36,height:36,borderRadius:11,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},eventIconText:{color:c.accentBright,fontWeight:'900'},eventCopy:{flex:1},eventTitle:{color:c.text,fontSize:13,fontWeight:'800'},chevron:{color:c.muted,fontSize:25},status:{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1},inner:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:13,padding:12,gap:5},link:{color:c.accentBright,fontSize:9,fontWeight:'900'},meta:{color:c.muted,fontSize:11,lineHeight:17},delete:{color:c.danger,fontSize:8,fontWeight:'900',letterSpacing:1},checkRow:{flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:c.border,paddingVertical:9},check:{width:26,height:26,borderRadius:8,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},checkDone:{backgroundColor:c.accent,borderColor:c.accent},checkText:{color:'#fff',fontWeight:'900'},checkLabel:{color:c.text,flex:1,fontSize:12},done:{textDecorationLine:'line-through',color:c.muted},message:{color:c.accentBright,fontSize:11},empty:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:16,padding:17},emptyTitle:{color:c.text,fontSize:13,fontWeight:'800'}
});
