import { useCallback,useEffect,useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { Screen,Header,c } from '@/components/mobile-ui';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

export default function ConversationScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const {session}=useAuth();const [messages,setMessages]=useState<any[]>([]);const [members,setMembers]=useState<any[]>([]);const [title,setTitle]=useState('Conversation');const [body,setBody]=useState('');
 const load=useCallback(async()=>{if(!id)return;const [{data:ms},{data:conv},{data:mem}]=await Promise.all([supabase.from('messages').select('id,sender_id,body,created_at').eq('conversation_id',id).order('created_at',{ascending:true}),supabase.from('conversations').select('id,kind,name').eq('id',id).maybeSingle(),supabase.from('conversation_members').select('user_id').eq('conversation_id',id)]);setMessages(ms||[]);setMembers(mem||[]);if(conv?.name)setTitle(conv.name);else if(mem?.length===2){const other=mem.find((m:any)=>m.user_id!==session?.user.id);if(other){const {data:p}=await supabase.from('profiles').select('full_name').eq('user_id',other.user_id).maybeSingle();setTitle(p?.full_name||'Direct chat')}}},[id,session?.user.id]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer)},[load]);
 async function send(){if(!session||!id||!body.trim())return;const text=body.trim();setBody('');const {error}=await supabase.from('messages').insert({conversation_id:id,sender_id:session.user.id,body:text});if(error)setBody(text);else await load()}
 return <Screen><Header eyebrow="MESSAGES" title={title} subtitle={members.length>2?'Group conversation':'Private conversation'}/><View style={{flex:1,gap:8}}>{messages.map(m=><View key={m.id} style={{alignSelf:m.sender_id===session?.user.id?'flex-end':'flex-start',maxWidth:'82%',backgroundColor:m.sender_id===session?.user.id?c.accent:c.surface,borderRadius:14,padding:10}}><Text style={{color:'#fff',fontSize:13}}>{m.body}</Text><Text style={{color:'#D0D8E6',fontSize:8,marginTop:4}}>{new Date(m.created_at).toLocaleString()}</Text></View>)}</View><View style={{flexDirection:'row',gap:7,alignItems:'flex-end',marginTop:12}}><TextInput value={body} onChangeText={setBody} multiline placeholder="Message…" placeholderTextColor={c.muted} style={{flex:1,minHeight:45,maxHeight:100,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:11}}/><Pressable onPress={()=>void send()} style={{backgroundColor:c.accent,borderRadius:12,padding:13}}><Text style={{color:'#fff',fontWeight:'900'}}>SEND</Text></Pressable></View></Screen>
}