import { useCallback,useEffect,useState } from 'react';
import { Alert,ActivityIndicator,Linking,Pressable,Text,TextInput,View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,Empty,c } from '@/components/mobile-ui';

export default function DocumentsScreen(){
 const {session}=useAuth();const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [title,setTitle]=useState('');
 const load=useCallback(async()=>{if(!session)return;const {data,error}=await supabase.from('documents').select('id,title,document_type,issued_at,expires_at,file_path,notes').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)setMessage(error.message);setRows(data||[])},[session]);
 useEffect(()=>{void load()},[load]);
 async function uploadAsset(asset:any,type='document'){
  if(!session||!asset?.uri)return;setBusy(true);setMessage('');
  try{const name=String(asset.name||asset.fileName||'document').replace(/[^a-zA-Z0-9._-]/g,'_');const path=session.user.id+'/'+Date.now()+'-'+name;const response=await fetch(asset.uri);const body=await response.arrayBuffer();const contentType=asset.mimeType||asset.type||'application/octet-stream';const up=await supabase.storage.from('documents').upload(path,body,{contentType,upsert:false,cacheControl:'3600'});if(up.error)throw up.error;const docTitle=title.trim()||name.replace(/\.[^.]+$/,'')||'Athlete document';const ins=await supabase.from('documents').insert({user_id:session.user.id,title:docTitle,document_type:type,file_path:path,notes:null});if(ins.error){await supabase.storage.from('documents').remove([path]);throw ins.error}setTitle('');setMessage('Document added securely.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Could not add document.')}finally{setBusy(false)}
 }
 async function camera(){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){setMessage('Camera permission is required to scan a document.');return}const r=await ImagePicker.launchCameraAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.9});if(r.canceled||!r.assets[0])return;await uploadAsset({uri:r.assets[0].uri,name:'camera-document-'+Date.now()+'.jpg',mimeType:'image/jpeg'},'camera')}
 async function chooseFile(){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(r.canceled||!r.assets?.[0])return;await uploadAsset(r.assets[0],'file')}
 async function open(x:any){if(!x.file_path)return;const {data,error}=await supabase.storage.from('documents').createSignedUrl(x.file_path,300);if(error||!data?.signedUrl){setMessage(error?.message||'Could not open secure file.');return}await Linking.openURL(data.signedUrl)}
 async function remove(x:any){Alert.alert('Delete document?','Delete '+x.title+' permanently from your AthleteN document vault?',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{setBusy(true);const db=await supabase.from('documents').delete().eq('id',x.id).eq('user_id',session?.user.id);if(!db.error&&x.file_path)await supabase.storage.from('documents').remove([x.file_path]);setBusy(false);if(db.error)setMessage(db.error.message);else{setMessage('Document deleted.');await load()}}}])}
 return <Screen><Header eyebrow="ATHLETEN TRUST" title="Documents" subtitle="Add certificates and athlete records using your camera or a file."/><Section title="ADD DOCUMENT"><Card><Text style={{color:c.text,fontSize:12,fontWeight:'900'}}>Document title</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g. Tournament certificate" placeholderTextColor={c.muted} style={{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:11,color:c.text,padding:11,fontSize:12}}/><View style={{flexDirection:'row',gap:8}}><Pressable disabled={busy} onPress={()=>void camera()} style={{flex:1,backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'}}><Text style={{color:'#fff',fontSize:9,fontWeight:'900'}}>CAMERA</Text></Pressable><Pressable disabled={busy} onPress={()=>void chooseFile()} style={{flex:1,borderWidth:1,borderColor:c.border,borderRadius:12,padding:13,alignItems:'center'}}><Text style={{color:c.text,fontSize:9,fontWeight:'900'}}>SELECT FILE</Text></Pressable></View>{busy?<ActivityIndicator color={c.accent}/>:null}{message?<Text style={{color:c.accentBright,fontSize:10}}>{message}</Text>:null}</Card></Section><Section title="DOCUMENT VAULT">{rows.length?rows.map(x=><Card key={x.id}><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.title}</Text><Text style={{color:c.muted,fontSize:10}}>{x.document_type} • {x.expires_at?'Expires '+x.expires_at:'No expiry set'}</Text><View style={{flexDirection:'row',gap:16}}>{x.file_path?<Pressable onPress={()=>void open(x)}><Text style={{color:c.accentBright,fontSize:9,fontWeight:'900',marginTop:4}}>OPEN SECURE FILE ›</Text></Pressable>:null}<Pressable onPress={()=>void remove(x)}><Text style={{color:c.danger,fontSize:9,fontWeight:'900',marginTop:4}}>DELETE</Text></Pressable></View></Card>):<Empty text="No documents saved yet."/>}</Section></Screen>
}