import { useCallback,useEffect,useState } from 'react';
import { Pressable,Text,TextInput,View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';

export default function MessagesScreen(){
 const {session}=useAuth();const [conversations,setConversations]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [messages,setMessages]=useState<any[]>([]);const [body,setBody]=useState('');const [search,setSearch]=useState('');const [users,setUsers]=useState<any[]>([]);const [error,setError]=useState('');const [groupName,setGroupName]=useState('');const [groupCodes,setGroupCodes]=useState('');const [showGroup,setShowGroup]=useState(false);
 const load=useCallback(async()=>{if(!session)return;const {data,error:e}=await supabase.from('conversations').select('id,kind,name,created_by,created_at').order('created_at',{ascending:false});if(e){setError(e.message);setConversations([]);return}const rows=data||[];const ids=rows.map((x:any)=>x.id);if(!ids.length){setConversations([]);return}const {data:members,error:me}=await supabase.from('conversation_members').select('conversation_id,user_id').in('conversation_id',ids);if(me)setError(me.message);const userIds=[...new Set((members||[]).map((m:any)=>m.user_id).filter((id:string)=>id!==session.user.id))];const {data:profiles,error:pe}=userIds.length?await supabase.from('profiles').select('user_id,full_name,username,account_code').in('user_id',userIds):{data:[],error:null} as any;if(pe)setError(pe.message);const byId=new Map((profiles||[]).map((p:any)=>[p.user_id,p]));const enriched=rows.map((row:any)=>{if(row.kind==='group')return row;const member=(members||[]).find((m:any)=>m.conversation_id===row.id&&m.user_id!==session.user.id);const person=member?byId.get(member.user_id):null;return {...row,display_name:person?.full_name||person?.username||person?.account_code||'Direct conversation'}});setConversations(enriched)},[session]);useEffect(()=>{void load()},[load]);
 const open=async(id:string)=>{const c0=conversations.find(x=>x.id===id);setSelected(c0||null);const {data}=await supabase.from('messages').select('id,sender_id,body,message_type,created_at').eq('conversation_id',id).order('created_at',{ascending:true});setMessages(data||[])};
 async function find(){if(search.trim().length<2){setUsers([]);return}const {data,error:e}=await supabase.rpc('search_messaging_users',{p_query:search.trim()});if(e)setError(e.message);setUsers(data||[])}
 async function start(user:any){const {data,error:e}=await supabase.rpc('create_direct_conversation_by_user',{p_recipient_id:user.user_id});if(e){setError(e.message);return}await load();setSearch('');setUsers([]);if(data)await open(String(data))}
 async function createGroup(){if(!session||!groupName.trim())return;const codes=groupCodes.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);const ids:string[]=[];for(const code of codes){const r=await supabase.rpc('find_user_by_account_code',{p_code:code});if(r.error){setError(r.error.message);return}const u=r.data?.[0];if(u?.user_id&&u.user_id!==session.user.id)ids.push(u.user_id)}const unique=[...new Set(ids)];if(!unique.length){setError('Enter at least one valid account code.');return}const created=await supabase.from('conversations').insert({kind:'group',name:groupName.trim(),created_by:session.user.id}).select('id').single();if(created.error){setError(created.error.message);return}const members=[session.user.id,...unique].map(user_id=>({conversation_id:created.data.id,user_id}));const m=await supabase.from('conversation_members').insert(members);if(m.error){setError(m.error.message);return}setGroupName('');setGroupCodes('');setShowGroup(false);await load();await open(created.data.id)}
 async function send(){if(!session||!selected||!body.trim())return;const {error:e}=await supabase.from('messages').insert({conversation_id:selected.id,sender_id:session.user.id,body:body.trim(),message_type:'normal'});if(e)setError(e.message);else{setBody('');await open(selected.id)}}
 return <Screen><Header back eyebrow="ATHLETEN COMMUNITY" title="Messages & Groups" subtitle="Private coach communication, direct chats and coaching groups."/>
 <Section title="START A CHAT"><Card><TextInput value={search} onChangeText={v=>{setSearch(v);void find()}} placeholder="Search name, username or account code" placeholderTextColor={c.muted} style={i}/>{users.map(u=><Pressable key={u.user_id} onPress={()=>void start(u)} style={{paddingVertical:10,borderBottomWidth:1,borderBottomColor:c.border}}><Text style={{color:c.text,fontWeight:'900'}}>{u.full_name||u.username||'User'}</Text><Text style={{color:c.muted,fontSize:9}}>{u.username ? '@'+u.username+' · ' : ''}{u.account_code||''}</Text></Pressable>)}<Pressable onPress={()=>setShowGroup(v=>!v)} style={groupBtn}><Text style={{color:c.accentBright,fontWeight:'900'}}>{showGroup?'CLOSE':'CREATE COACHING GROUP'}</Text></Pressable>{showGroup?<View style={{gap:8,marginTop:8}}><TextInput value={groupName} onChangeText={setGroupName} placeholder="Group name" placeholderTextColor={c.muted} style={i}/><TextInput value={groupCodes} onChangeText={setGroupCodes} placeholder="Account codes, separated by spaces or commas" placeholderTextColor={c.muted} style={i}/><Pressable onPress={()=>void createGroup()} style={primary}><Text style={{color:'#fff',fontWeight:'900'}}>CREATE GROUP</Text></Pressable></View>:null}</Card></Section>
 <Section title="CONVERSATIONS">{conversations.length?conversations.map(x=><Pressable key={x.id} onPress={()=>void open(x.id)}><Card><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.kind==='group'?x.name||'Group':x.display_name||'Direct conversation'}</Text><Text style={{color:c.muted,fontSize:9}}>{x.kind==='group'?'PRIVATE GROUP':'1:1 PRIVATE CHAT'}</Text></Card></Pressable>):<Card><Text style={{color:c.muted,fontSize:11}}>No conversations yet.</Text></Card>}</Section>
 {selected?<Section title={selected.kind==='group'?selected.name||'Group':selected.display_name||'Private conversation'}><Card>{messages.map(m=><View key={m.id} style={{paddingVertical:8,borderBottomWidth:1,borderBottomColor:c.border}}><Text style={{color:m.sender_id===session?.user.id?c.accentBright:c.text,fontSize:9,fontWeight:'900'}}>{m.sender_id===session?.user.id?'YOU':'MEMBER'}</Text><Text style={{color:c.text,fontSize:12,lineHeight:17}}>{m.body}</Text></View>)}<View style={{flexDirection:'row',gap:8,marginTop:10}}><TextInput value={body} onChangeText={setBody} placeholder="Write a message..." placeholderTextColor={c.muted} style={{flex:1,backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:11}}/><Pressable onPress={()=>void send()} style={{backgroundColor:c.accent,borderRadius:12,paddingHorizontal:16,justifyContent:'center'}}><Text style={{color:'#fff',fontWeight:'900'}}>SEND</Text></Pressable></View></Card></Section>:null}
 {error?<Text style={{color:c.danger,fontSize:10}}>{error}</Text>:null}
 </Screen>
}
const i={backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:12,fontSize:12} as any;
const groupBtn={marginTop:9,borderWidth:1,borderColor:c.accentDeep,borderRadius:12,padding:12,alignItems:'center',backgroundColor:c.accentSoft} as any;
const primary={backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'} as any;