import { useCallback,useEffect,useState } from 'react';
import { Pressable,Text,TextInput,View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';
export default function MessagesScreen(){const {session}=useAuth();const [conversations,setConversations]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [messages,setMessages]=useState<any[]>([]);const [body,setBody]=useState('');const [search,setSearch]=useState('');const [users,setUsers]=useState<any[]>([]);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!session)return;const {data,error:e}=await supabase.from('conversations').select('id,kind,name,created_by,created_at').order('created_at',{ascending:false});if(e)setError(e.message);setConversations(data||[])},[session]);useEffect(()=>{void load()},[load]);
 const open=async(id:string)=>{const c0=conversations.find(x=>x.id===id);setSelected(c0||null);const {data}=await supabase.from('messages').select('id,sender_id,body,message_type,created_at').eq('conversation_id',id).order('created_at',{ascending:true});setMessages(data||[])};
 async function find(){if(search.trim().length<2){setUsers([]);return}const {data,error:e}=await supabase.rpc('search_messaging_users',{p_query:search.trim()});if(e)setError('User search unavailable.');setUsers(data||[])}
 async function start(user:any){const {data,error:e}=await supabase.rpc('create_direct_conversation_by_user',{p_recipient_id:user.user_id});if(e){setError(e.message);return}await load();setSearch('');setUsers([]);if(data)await open(String(data))}
 async function send(){if(!session||!selected||!body.trim())return;const {error:e}=await supabase.from('messages').insert({conversation_id:selected.id,sender_id:session.user.id,body:body.trim(),message_type:'normal'});if(e)setError(e.message);else{setBody('');await open(selected.id)}}
 return <Screen><Header eyebrow="ATHLETEN COMMUNITY" title="Messages" subtitle="Secure conversations with athletes, coaches and teams."/><Section title="FIND AN ATHLETE"><Card><TextInput value={search} onChangeText={v=>{setSearch(v);void find()}} placeholder="@username" placeholderTextColor={c.muted} style={{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:12}}/>{users.map(u=><Pressable key={u.user_id} onPress={()=>void start(u)} style={{paddingVertical:10}}><Text style={{color:c.text,fontWeight:'900'}}>@{u.username}</Text><Text style={{color:c.muted,fontSize:10}}>{u.full_name}</Text></Pressable>)}</Card></Section><Section title="CONVERSATIONS">{conversations.length?conversations.map(x=><Pressable key={x.id} onPress={()=>void open(x.id)}><Card><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.kind==='group'?x.name||'Group':'Private conversation'}</Text><Text style={{color:c.muted,fontSize:9}}>{x.kind==='group'?'Group':'1:1'}</Text></Card></Pressable>):<Card><Text style={{color:c.muted,fontSize:11}}>No conversations yet.</Text></Card>}</Section>{selected?<Section title={selected.kind==='group'?selected.name||'Group':'Private conversation'}><Card>{messages.map(m=><View key={m.id} style={{paddingVertical:8,borderBottomWidth:1,borderBottomColor:c.border}}><Text style={{color:m.sender_id===session?.user.id?c.accentBright:c.text,fontSize:9,fontWeight:'900'}}>{m.sender_id===session?.user.id?'YOU':'ATHLETE'}</Text><Text style={{color:c.text,fontSize:12,lineHeight:17}}>{m.body}</Text></View>)}<View style={{flexDirection:'row',gap:8,marginTop:10}}><TextInput value={body} onChangeText={setBody} placeholder="Write a message..." placeholderTextColor={c.muted} style={{flex:1,backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:12,color:c.text,padding:11}}/><Pressable onPress={()=>void send()} style={{backgroundColor:c.accent,borderRadius:12,paddingHorizontal:16,justifyContent:'center'}}><Text style={{color:'#fff',fontWeight:'900'}}>SEND</Text></Pressable></View>{error?<Text style={{color:c.danger,fontSize:10,marginTop:8}}>{error}</Text>:null}</Card></Section>:null}</Screen>}
