import { useCallback,useEffect,useState } from 'react';
import { Pressable,Text } from 'react-native';
import { useRef } from 'react';
import * as Notifications from 'expo-notifications';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Card,Empty,c } from '@/components/mobile-ui';
Notifications.setNotificationHandler({handleNotification:async()=>({shouldPlaySound:true,shouldSetBadge:true,shouldShowBanner:true,shouldShowList:true})});
export default function NotificationsScreen(){const {session}=useAuth();const channelRef=useRef<any>(null);const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{if(!session)return;const {data}=await supabase.from('notifications').select('id,title,body,created_at,read_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(50);setRows(data||[])},[session]);useEffect(()=>{void load();if(!session)return;void (async()=>{const p=await Notifications.requestPermissionsAsync();if(p.granted&&Notifications.setBadgeCountAsync)await Notifications.setBadgeCountAsync(0)})();const channel=supabase.channel('mobile-notifications-'+session.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:'user_id=eq.'+session.user.id},payload=>{const n:any=payload.new;void load();void Notifications.scheduleNotificationAsync({content:{title:n?.title||'AthleteN',body:n?.body||'You have a new notification.',sound:'default'},trigger:null})}).subscribe();channelRef.current=channel;return()=>{void supabase.removeChannel(channel)}} , [load,session]);async function read(x:any){await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',x.id).eq('user_id',session?.user.id);await load()}return <Screen><Header eyebrow="ATHLETEN CENTER" title="Notifications" subtitle="Competition, account and platform updates."/><>{rows.length?rows.map(x=><Pressable key={x.id} onPress={()=>void read(x)}><Card><Text style={{color:x.read_at?c.muted:c.text,fontSize:14,fontWeight:'900'}}>{x.title}</Text>{x.body?<Text style={{color:c.muted,fontSize:11,lineHeight:17}}>{x.body}</Text>:null}<Text style={{color:c.muted,fontSize:8,marginTop:3}}>{x.created_at?new Date(x.created_at).toLocaleString():'—'}{x.read_at?' • READ':' • NEW'}</Text></Card></Pressable>):<Empty text="No notifications yet."/>}</></Screen>}
