import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
const c = Colors.dark;
export default function NutritionScreen() {
 const { session } = useAuth(); const router = useRouter();
 const [enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [mealType,setMealType]=useState('meal'),[note,setNote]=useState(''),[calories,setCalories]=useState(''),[protein,setProtein]=useState(''),[carbs,setCarbs]=useState(''),[fat,setFat]=useState(''),[water,setWater]=useState('');
 const [meals,setMeals]=useState<any[]>([]),[waterLogs,setWaterLogs]=useState<any[]>([]);
 const today=()=>new Date().toISOString().slice(0,10);
 const load=useCallback(async()=>{if(!session)return;setLoading(true);const control=await supabase.from('athlete_feature_controls').select('enabled').eq('athlete_user_id',session.user.id).eq('feature_key','nutrition').maybeSingle();const on=control.data?.enabled===true;setEnabled(on);if(on){const [m,h]=await Promise.all([supabase.from('nutrition_logs').select('id,log_date,meal_type,meal_note,calories,protein_g,carbs_g,fat_g').eq('user_id',session.user.id).eq('log_date',today()).order('created_at',{ascending:false}),supabase.from('hydration_logs').select('id,log_date,water_ml,note').eq('user_id',session.user.id).eq('log_date',today()).order('created_at',{ascending:false})]);if(m.error||h.error)setMessage(m.error?.message||h.error?.message||'Could not load nutrition data.');setMeals(m.data||[]);setWaterLogs(h.data||[])}setLoading(false)},[session]);
 useEffect(()=>{void load()},[load]);
 async function addMeal(){if(!session)return;const item={user_id:session.user.id,log_date:today(),meal_type:mealType,meal_note:note.trim()||null,calories:calories.trim()?Number(calories):null,protein_g:protein.trim()?Number(protein):null,carbs_g:carbs.trim()?Number(carbs):null,fat_g:fat.trim()?Number(fat):null};if(item.calories!==null&&(!Number.isFinite(item.calories)||item.calories<0)){setMessage('Enter valid calories.');return}setBusy(true);const {error}=await supabase.from('nutrition_logs').insert(item);setBusy(false);if(error)setMessage(error.message);else{setNote('');setCalories('');setProtein('');setCarbs('');setFat('');setMessage('Meal saved.');await load()}}
 async function addWater(){if(!session)return;const ml=Number(water);if(!Number.isFinite(ml)||ml<=0){setMessage('Enter a valid water amount.');return}setBusy(true);const {error}=await supabase.from('hydration_logs').insert({user_id:session.user.id,log_date:today(),water_ml:Math.round(ml)});setBusy(false);if(error)setMessage(error.message);else{setWater('');setMessage('Hydration saved.');await load()}}
 async function remove(table:'nutrition_logs'|'hydration_logs',id:string){setBusy(true);const {error}=await supabase.from(table).delete().eq('id',id).eq('user_id',session?.user.id);setBusy(false);if(error)setMessage(error.message);else await load()}
 const totalCalories=meals.reduce((sum,m)=>sum+(Number(m.calories)||0),0),totalProtein=meals.reduce((sum,m)=>sum+(Number(m.protein_g)||0),0),totalWater=waterLogs.reduce((sum,h)=>sum+(Number(h.water_ml)||0),0);
 if(loading)return <View style={s.center}><ActivityIndicator color={c.accent}/><Text style={s.meta}>Loading nutrition access…</Text></View>;
 if(!enabled)return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.kicker}>ATHLETEN • NUTRITION</Text><Text style={s.title}>Coach-controlled</Text><Text style={s.subtitle}>Nutrition and calorie logging is not enabled for your account yet. Your coach can add it when they decide it is appropriate for your training.</Text><View style={s.lockCard}><Text style={s.lockIcon}>◈</Text><Text style={s.lockTitle}>Waiting for coach</Text><Text style={s.meta}>No calorie targets, restrictions, or nutrition tracking are shown until your coach enables the feature.</Text></View><Pressable style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>GO BACK</Text></Pressable></ScrollView>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View><Text style={s.kicker}>ATHLETEN • NUTRITION</Text><Text style={s.title}>Fuel & hydration</Text><Text style={s.subtitle}>Log what you eat and drink. Calorie and macro fields are optional.</Text></View><View style={s.summaryRow}><Metric label="CALORIES LOGGED" value={totalCalories?String(totalCalories):'—'}/><Metric label="PROTEIN" value={totalProtein?totalProtein.toFixed(0)+' g':'—'}/><Metric label="WATER" value={totalWater?(totalWater/1000).toFixed(1)+' L':'—'}/></View><View style={s.card}><Text style={s.cardTitle}>LOG A MEAL</Text><View style={s.chips}>{['breakfast','lunch','dinner','snack'].map(x=><Pressable key={x} onPress={()=>setMealType(x)} style={[s.chip,mealType===x&&s.chipActive]}><Text style={[s.chipText,mealType===x&&s.chipTextActive]}>{x.toUpperCase()}</Text></Pressable>)}</View><Field label="Meal note" value={note} onChangeText={setNote} placeholder="What did you have?"/><View style={s.grid}><Field label="Calories (optional)" value={calories} onChangeText={setCalories} placeholder="—" keyboardType="number-pad"/><Field label="Protein g" value={protein} onChangeText={setProtein} placeholder="—" keyboardType="decimal-pad"/></View><View style={s.grid}><Field label="Carbs g" value={carbs} onChangeText={setCarbs} placeholder="—" keyboardType="decimal-pad"/><Field label="Fat g" value={fat} onChangeText={setFat} placeholder="—" keyboardType="decimal-pad"/></View><Button title="SAVE MEAL" onPress={addMeal} busy={busy}/></View><View style={s.card}><Text style={s.cardTitle}>HYDRATION</Text><Field label="Water added" value={water} onChangeText={setWater} placeholder="ml" keyboardType="number-pad"/><Button title="LOG WATER" onPress={addWater} busy={busy}/>{waterLogs.map(x=><Row key={x.id} title={x.water_ml+' ml'} sub={x.log_date} onDelete={()=>remove('hydration_logs',x.id)}/>)}</View><View style={s.card}><Text style={s.cardTitle}>TODAY'S LOG</Text>{!meals.length?<Text style={s.meta}>No meals logged today.</Text>:meals.map(x=><Row key={x.id} title={x.meal_type.toUpperCase()+(x.calories!=null?' • '+x.calories+' kcal':'')} sub={x.meal_note||'No note'} onDelete={()=>remove('nutrition_logs',x.id)}/>)}</View>{message?<Text style={s.message}>{message}</Text>:null}</ScrollView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
function Field({label,value,onChangeText,placeholder,keyboardType}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} keyboardType={keyboardType} style={s.input}/></View>}
function Button({title,onPress,busy}:{title:string;onPress:()=>void;busy:boolean}){return <Pressable onPress={onPress} disabled={busy} style={s.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{title}</Text>}</Pressable>}
function Row({title,sub,onDelete}:{title:string;sub:string;onDelete:()=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.meta}>{sub}</Text></View><Pressable onPress={onDelete}><Text style={s.delete}>DELETE</Text></Pressable></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.background},content:{padding:18,paddingBottom:50,gap:12},center:{flex:1,backgroundColor:c.background,alignItems:'center',justifyContent:'center',gap:10},kicker:{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:c.text,fontSize:28,fontWeight:'900',marginTop:3},subtitle:{color:c.muted,fontSize:12,lineHeight:18},summaryRow:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:15,padding:12},metricLabel:{color:c.muted,fontSize:7,fontWeight:'900',letterSpacing:.7},metricValue:{color:c.text,fontSize:18,fontWeight:'900',marginTop:5},card:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:18,padding:15,gap:10},cardTitle:{color:c.text,fontSize:11,fontWeight:'900',letterSpacing:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:c.border,borderRadius:999,paddingHorizontal:10,paddingVertical:8},chipActive:{backgroundColor:c.accentSoft,borderColor:c.accent},chipText:{color:c.textSecondary,fontSize:8,fontWeight:'900'},chipTextActive:{color:c.accentBright},grid:{flexDirection:'row',gap:8},field:{flex:1,gap:5},label:{color:c.textSecondary,fontSize:9,fontWeight:'800'},input:{backgroundColor:c.background,borderWidth:1,borderColor:c.border,borderRadius:11,color:c.text,padding:10,fontSize:12},button:{backgroundColor:c.accent,borderRadius:11,padding:12,alignItems:'center'},buttonText:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},row:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:c.border,paddingTop:9},rowTitle:{color:c.text,fontSize:12,fontWeight:'800'},delete:{color:c.danger,fontSize:8,fontWeight:'900'},message:{color:c.accentBright,fontSize:11},lockCard:{backgroundColor:c.surface,borderWidth:1,borderColor:c.borderStrong,borderRadius:19,padding:18,gap:8},lockIcon:{color:c.accentBright,fontSize:25},lockTitle:{color:c.text,fontSize:17,fontWeight:'900'},secondary:{borderWidth:1,borderColor:c.border,borderRadius:12,padding:13,alignItems:'center'},secondaryText:{color:c.text,fontSize:9,fontWeight:'900',letterSpacing:1},meta:{color:c.muted,fontSize:11,lineHeight:17}});
