import { useCallback,useEffect,useState } from 'react';
import { Text,View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Section,Card,c } from '@/components/mobile-ui';
import { PerformanceBars,PerformanceLine } from '@/components/performance-chart';
export default function TaekwondoScreen(){
 const {session,profile}=useAuth(); const [bouts,setBouts]=useState<any[]>([]); const [poomsae,setPoomsae]=useState<any[]>([]); const [training,setTraining]=useState<any[]>([]);
 const load=useCallback(async()=>{if(!session)return;const uid=session.user.id;const [b,p,t]=await Promise.all([supabase.from('kyorugi_bouts').select('*').eq('user_id',uid).order('event_date',{ascending:false}).limit(50),supabase.from('poomsae_performances').select('*').eq('user_id',uid).order('event_date',{ascending:false}).limit(50),supabase.from('taekwondo_training_logs').select('*').eq('user_id',uid).order('session_date',{ascending:false}).limit(50)]);setBouts(b.data||[]);setPoomsae(p.data||[]);setTraining(t.data||[])},[session]);
 useEffect(()=>{void load()},[load]); const kyorugi=profile?.discipline!=='Poomsae'; const wins=bouts.filter(x=>x.result==='win').length,losses=bouts.filter(x=>x.result==='loss').length;
 return <Screen><Header eyebrow="TAEKWONDO EDITION" title="Taekwondo Hub" subtitle={(profile?.discipline||'Kyorugi')+'-specific performance workspace.'}/>
 <Card accent><Text style={{color:c.accentBright,fontSize:9,fontWeight:'900',letterSpacing:1}}>ACTIVE DISCIPLINE</Text><Text style={{color:c.text,fontSize:23,fontWeight:'900'}}>{profile?.discipline||'Kyorugi'}</Text><Text style={{color:'#BBD6FF',fontSize:11,lineHeight:17}}>{kyorugi?'Bout results, rounds, opponents and competition performance.':'Poomsae performances, scores, placings and technical training.'}</Text></Card>
 {kyorugi?<><View style={{flexDirection:'row',gap:9}}><Stat label="BOUTS" value={bouts.length}/><Stat label="WINS" value={wins}/><Stat label="LOSSES" value={losses}/></View><PerformanceBars title="Bout record" subtitle="Saved bout outcomes" data={[{label:'Wins',value:wins},{label:'Losses',value:losses}]} unit=""/><Section title="RECENT BOUTS">{bouts.slice(0,8).map(x=><Card key={x.id}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.opponent_name||'Opponent not set'}</Text><Text style={{color:x.result==='win'?c.success:x.result==='loss'?c.danger:c.warning,fontWeight:'900',fontSize:9}}>{String(x.result||'pending').toUpperCase()}</Text></View><Text style={{color:c.muted,fontSize:10}}>{x.event_name||'Event'} • {x.event_date||'Date not set'}{x.athlete_score!=null?' • '+x.athlete_score+'-'+x.opponent_score:''}</Text></Card>)}</Section></>:<><View style={{flexDirection:'row',gap:9}}><Stat label="PERFORMANCES" value={poomsae.length}/><Stat label="MEDALS" value={poomsae.filter(x=>['gold','silver','bronze'].includes(x.result)).length}/><Stat label="TRAINING LOGS" value={training.length}/></View><PerformanceLine title="Poomsae scores" subtitle="Saved performance scores" data={poomsae.slice(-10).map(x=>({label:String(x.event_date||'').slice(5,10),value:Number(x.score||0)}))} unit=""/><Section title="RECENT PERFORMANCES">{poomsae.slice(0,8).map(x=><Card key={x.id}><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.poomsae_name||'Poomsae performance'}</Text><Text style={{color:c.muted,fontSize:10}}>{x.event_name||'Event'} • {x.event_date||'Date not set'} • Score {x.score??'—'} • {x.placing?'Place '+x.placing:'Not placed'}</Text></Card>)}</Section></>}
 <Section title="TAEKWONDO TRAINING">{training.slice(0,8).map(x=><Card key={x.id}><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{x.title}</Text><Text style={{color:c.muted,fontSize:10}}>{x.session_date} • {x.focus||'General'}{x.rounds?' • '+x.rounds+' rounds':''}{x.repetitions?' • '+x.repetitions+' reps':''}</Text></Card>)}</Section>
 </Screen>}
function Stat({label,value}:{label:string;value:number}){return <View style={{flex:1,backgroundColor:c.surfaceRaised,borderWidth:1,borderColor:c.border,borderRadius:17,padding:13}}><Text style={{color:c.text,fontSize:21,fontWeight:'900'}}>{value}</Text><Text style={{color:c.muted,fontSize:7,fontWeight:'900',letterSpacing:1}}>{label}</Text></View>}
