import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Linking,Pressable,Text,View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { Screen,Header,Card,Section,Empty,c } from '@/components/mobile-ui';

const PROOFS=[['school_id','School ID'],['fee_receipt','Fee receipt'],['bonafide','Bonafide certificate']];

export default function VerificationScreen(){
 const {session}=useAuth();const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [proof,setProof]=useState('school_id');
 const load=useCallback(async()=>{if(!session)return;const {data,error}=await supabase.from('student_verifications').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error){setMessage(error.message);return}setRows(data||[])},[session]);
 useEffect(()=>{void load();if(!session)return;const channel=supabase.channel('mobile-verification-'+session.user.id).on('postgres_changes',{event:'*',schema:'public',table:'student_verifications',filter:'user_id=eq.'+session.user.id},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load,session]);
 async function choose(){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false,type:['application/pdf','image/jpeg','image/png','image/webp']});if(r.canceled||!r.assets?.[0]||!session)return;const asset=r.assets[0];setBusy(true);setMessage('');let path='';try{const name=String(asset.name||'proof').replace(/[^a-zA-Z0-9._-]/g,'_');path=session.user.id+'/'+Date.now()+'-'+name;const response=await fetch(asset.uri);if(!response.ok)throw new Error('Could not read the selected proof file.');const blob=await response.blob();const contentType=asset.mimeType||blob.type||'application/octet-stream';const up=await supabase.storage.from('verification-proofs').upload(path,blob,{contentType,upsert:false,cacheControl:'3600'});if(up.error)throw new Error('Upload failed: '+up.error.message);const ins=await supabase.from('student_verifications').insert({user_id:session.user.id,document_type:proof,file_path:path,status:'pending'});if(ins.error){await supabase.storage.from('verification-proofs').remove([path]);throw new Error('Verification record failed: '+ins.error.message)}setMessage('Proof submitted. It is now pending review and will appear on the website automatically.');await load()}catch(e){if(path)await supabase.storage.from('verification-proofs').remove([path]).catch(()=>undefined);setMessage(e instanceof Error?e.message:'Could not submit verification proof.')}finally{setBusy(false)}}
 async function openProof(x:any){if(!x.file_path)return;const {data,error}=await supabase.storage.from('verification-proofs').createSignedUrl(x.file_path,300);if(error||!data?.signedUrl){setMessage(error?.message||'Could not open proof.');return}await Linking.openURL(data.signedUrl)}
 return <Screen><Header eyebrow="ATHLETEN TRUST" title="Verification" subtitle="Submit the same proof types used by the AthleteN website."/><Card accent><Text style={{color:c.accentBright,fontSize:8,fontWeight:'900',letterSpacing:1}}>VERIFICATION STATUS</Text><Text style={{color:c.text,fontSize:21,fontWeight:'900'}}>{rows[0]?.status?String(rows[0].status).toUpperCase():'NOT SUBMITTED'}</Text><Text style={{color:'#BBD6FF',fontSize:10,lineHeight:16}}>{rows[0]?.reviewer_notes||'Submit a school ID, fee receipt, or bonafide certificate.'}</Text></Card><Section title="ADD PROOF"><Card><Text style={{color:c.text,fontSize:11,fontWeight:'900'}}>Proof type</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:8}}>{PROOFS.map(([id,label])=><Pressable key={id} onPress={()=>setProof(id)} style={{borderWidth:1,borderColor:proof===id?c.accent:c.border,borderRadius:10,paddingHorizontal:10,paddingVertical:8,backgroundColor:proof===id?c.accentSoft:c.background}}><Text style={{color:proof===id?c.accentBright:c.muted,fontSize:9,fontWeight:'900'}}>{label}</Text></Pressable>)}</View><Pressable disabled={busy} onPress={()=>void choose()} style={{marginTop:10,backgroundColor:c.accent,borderRadius:12,padding:13,alignItems:'center'}}><Text style={{color:'#fff',fontSize:9,fontWeight:'900'}}>{busy?'UPLOADING…':'CHOOSE PROOF FILE'}</Text></Pressable>{busy?<ActivityIndicator color={c.accent}/>:null}{message?<Text style={{color:c.accentBright,fontSize:10,marginTop:6}}>{message}</Text>:null}</Card></Section><Section title="HISTORY">{rows.length?rows.map(x=><Card key={x.id}><Text style={{color:c.text,fontSize:13,fontWeight:'900'}}>{PROOFS.find(p=>p[0]===x.document_type)?.[1]||x.document_type||'Verification request'}</Text><Text style={{color:c.muted,fontSize:10}}>{x.status||'pending'} • {x.created_at?new Date(x.created_at).toLocaleDateString():'—'}</Text>{x.file_path?<Pressable onPress={()=>void openProof(x)}><Text style={{color:c.accentBright,fontSize:9,fontWeight:'900',marginTop:5}}>OPEN PROOF ›</Text></Pressable>:null}</Card>):<Empty text="No verification requests are currently recorded."/>}</Section></Screen>
}