import { useEffect, useMemo, useState } from "react";
import { Ban, Flag, MessageCircle, Plus, Search, Send, Users } from "lucide-react";
import { requireSupabase } from "../../lib/supabase";
import { useAuth } from "../../hooks/useAuth";

type Conversation = { id: string; kind: "direct" | "group"; name?: string | null; created_by: string; created_at: string };
type Message = { id: string; conversation_id: string; sender_id: string; body: string; message_type: string; created_at: string };
type MessagingUser = { user_id: string; username: string; full_name: string; academy?: string | null; role: string };
type Props = { userId?: string; role?: string; setToast?: (toast: { type: "success" | "error" | "warning"; message: string }) => void };
const messageTypes = [["normal", "Normal message"], ["tournament_announcement", "Tournament announcement"], ["training_schedule", "Training schedule"], ["training_plan", "Training plan"], ["document", "Document"], ["team_announcement", "Team announcement"]] as const;
const usernamePattern = /^[a-z0-9][a-z0-9_.-]{2,29}$/;
const NOVACODE_USERNAME = "novacode.admin";

export default function MessagingPage({ userId, role, setToast }: Props) {
  const auth = useAuth(); const supabase = requireSupabase(); const effectiveUserId = userId || auth.user?.id; const notify = setToast || (() => undefined);
  const [conversations,setConversations]=useState<Conversation[]>([]); const [selectedId,setSelectedId]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [search,setSearch]=useState(""); const [users,setUsers]=useState<MessagingUser[]>([]); const [groupName,setGroupName]=useState(""); const [body,setBody]=useState(""); const [messageType,setMessageType]=useState("normal"); const [username,setUsername]=useState(""); const [usernameInput,setUsernameInput]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const selected=useMemo(()=>conversations.find((item)=>item.id===selectedId),[conversations,selectedId]); const canCreateGroup=["coach","academy_admin","admin","super_admin"].includes(role||""); const selectedIsGroupCreator=Boolean(selected?.kind==="group"&&selected.created_by===effectiveUserId);
  async function loadProfileUsername(){if(!effectiveUserId)return;const {data,error:queryError}=await supabase.from("profiles").select("username").eq("user_id",effectiveUserId).maybeSingle();if(queryError)throw queryError;const value=data?.username||"";setUsername(value);setUsernameInput(value);}
  async function saveUsername(){const value=usernameInput.trim().toLowerCase();if(!effectiveUserId)return;if(!usernamePattern.test(value)){setError("Username must be 3–30 characters and use only lowercase letters, numbers, dots, underscores, or hyphens.");return;}setBusy(true);setError("");try{const {data:current,error:currentError}=await supabase.from("profiles").select("full_name").eq("user_id",effectiveUserId).maybeSingle();if(currentError)throw currentError;if(!current)throw new Error("Profile could not be found. Please refresh and try again.");const {error:updateError}=await supabase.from("profiles").update({username:value,full_name:current.full_name}).eq("user_id",effectiveUserId);if(updateError)throw updateError;setUsername(value);setUsernameInput(value);notify({type:"success",message:`Your username is @${value}.`});}catch(e){setError(e instanceof Error?e.message:"Username could not be saved. It may already be taken.");}finally{setBusy(false);}}
  async function loadConversations(){if(!effectiveUserId)return;const {data,error:queryError}=await supabase.from("conversations").select("id, kind, name, created_by, created_at").order("created_at",{ascending:false});if(queryError)throw queryError;setConversations((data??[]) as Conversation[]);if(!selectedId&&data?.[0]?.id)setSelectedId(data[0].id);}
  async function loadMessages(conversationId:string){const {data,error:queryError}=await supabase.from("messages").select("id, conversation_id, sender_id, body, message_type, created_at").eq("conversation_id",conversationId).order("created_at",{ascending:true});if(queryError)throw queryError;setMessages((data??[]) as Message[]);}
