import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronRight, Database, FileCheck2, Megaphone, RefreshCw, Search, ShieldCheck, Ticket, Users, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { plans } from "../../config/plans";
import "./AdminControlCenter.css";

type Props = { userId: string; role: string };
type Row = Record<string, unknown>;
type Section = { key: string; label: string; table: string; group: string; deleteAllowed?: boolean };
type BillingState = { userId: string; planId: string; aiUsed: string; aiLimit: string; storageUsed: string; usageMonth: string; status: string; currentPeriodEnd: string };

const sections: Section[] = [
  ["profiles", "Users / Profiles", "profiles", "People"], ["academies", "Academies", "academies", "People"], ["academyMemberships", "Academy Memberships", "academy_memberships", "People"],
  ["training", "Training Sessions", "training_sessions", "Athlete data"], ["trainingPlans", "Training Plans", "training_plans", "Athlete data"], ["attendance", "Attendance", "attendance_records", "Athlete data"],
  ["tournaments", "Tournaments", "tournaments", "Competition"], ["matches", "Matches", "matches", "Competition"], ["medals", "Medals", "medals", "Competition"], ["certificates", "Certificates", "certificates", "Athlete data"],
  ["documents", "Documents", "documents", "Athlete data"], ["weights", "Weight Logs", "weight_logs", "Athlete data"], ["calendar", "Calendar", "calendar_events", "Athlete data"], ["notifications", "Notifications", "notifications", "Operations", false],
  ["checklist", "Competition Checklist", "competition_checklists", "Competition"], ["injuries", "Injuries", "injuries", "Athlete data"], ["goals", "Goals", "goals", "Athlete data"], ["feedback", "Feedback", "feedback_items", "Operations"],
  ["verifications", "Student Verification", "student_verifications", "Trust & safety"], ["roadmap", "Roadmap", "roadmap_items", "Product"], ["roadmapVotes", "Roadmap Votes", "roadmap_votes", "Product"], ["tournamentScans", "Tournament Scans", "tournament_scans", "Competition"],
  ["referrals", "Referrals", "referrals", "Growth"], ["badges", "Athlete Badges", "athlete_badges", "Growth"], ["aiUsage", "AI Usage", "ai_usage_events", "Usage & billing"], ["subscriptions", "Subscriptions", "subscriptions", "Usage & billing"],
  ["subscriptionUsage", "Subscription Usage", "subscription_usage", "Usage & billing"], ["paymentEvents", "Payment Events", "payment_events", "Usage & billing"], ["support", "Support Tickets", "support_tickets", "Operations", false], ["announcements", "Announcements", "announcements", "Operations"],
  ["featureFlags", "Feature Flags", "feature_flags", "System"], ["auditLogs", "Audit Logs", "audit_logs", "System", false],
].map(([key, label, table, group, deleteAllowed = true]) => ({ key, label, table, group, deleteAllowed }));
const groups = ["People", "Athlete data", "Competition", "Trust & safety", "Operations", "Usage & billing", "Product", "Growth", "System"];
const usageKeys = new Set(["subscriptionUsage", "subscriptions", "profiles"]);
const text = (v: unknown) => v === null || v === undefined ? "" : String(v);
const shown = (v: unknown) => v === null || v === undefined || v === "" ? "—" : typeof v === "object" ? JSON.stringify(v) : String(v);
const blankBilling = (): BillingState => ({ userId: "", planId: "free", aiUsed: "0", aiLimit: "0", storageUsed: "0", usageMonth: new Date().toISOString().slice(0, 10), status: "active", currentPeriodEnd: "" });
const editorLabel = (key: string) => key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const readOnlyEditorKeys = new Set(["id", "created_at", "updated_at"]);
const isDateEditorKey = (key: string) => /(^|_)(date|dob|birth|started|ended|expires|published|scheduled|period_end)($|_)/i.test(key);
const isLongEditorKey = (key: string) => /(^|_)(description|body|message|notes|reason|comment|bio|achievements)($|_)/i.test(key);
const isNumericEditorKey = (key: string) => /(^|_)(age|weight|height|score|placing|rank|amount|count|limit|used|points|duration|reps|rounds)($|_)/i.test(key);
const arrayEditorText = (value: unknown) => Array.isArray(value) ? value.map(v => String(v ?? "")).join("\n") : "";
const objectEditorText = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? Object.entries(value as Record<string, unknown>).map(([k, v]) => `${k}=${v ?? ""}`).join("\n") : "";
const parseObjectEditorText = (value: string) => Object.fromEntries(value.split("\n").map(line => line.trim()).filter(Boolean).map(line => { const i = line.indexOf("="); return i < 0 ? [line, ""] : [line.slice(0, i).trim(), line.slice(i + 1).trim()]; }));

export default function AdminControlCenter({ userId, role }: Props) {
  const [selected, setSelected] = useState("profiles"); const [rows, setRows] = useState<Row[]>([]); const [summaries, setSummaries] = useState<{ key: string; label: string; count: number }[]>([]);
  const [loading, setLoading] = useState(false); const [summaryLoading, setSummaryLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [query, setQuery] = useState(""); const [group, setGroup] = useState("All"); const [selectedRow, setSelectedRow] = useState<Row | null>(null); const [editorDraft, setEditorDraft] = useState<Row>({}); const [editorBusy, setEditorBusy] = useState(false);
  const [billing, setBilling] = useState<BillingState>(blankBilling()); const [billingBusy, setBillingBusy] = useState(false); const [announcementOpen, setAnnouncementOpen] = useState(false); const [announcement, setAnnouncement] = useState({ title: "", body: "", audience: "all" });
  const canManage = role === "admin" || role === "super_admin"; const isSuperAdmin = role === "super_admin"; const section = sections.find(s => s.key === selected) ?? sections[0];

  async function loadSummaries() { if (!supabase) return; setSummaryLoading(true); const r = await Promise.all(sections.map(async s => { const { count } = await supabase.from(s.table).select("id", { count: "exact", head: true }); return { key: s.key, label: s.label, count: count ?? 0 }; })); setSummaries(r); setSummaryLoading(false); }
  async function load() { if (!supabase) return; setLoading(true); setError(""); setSelectedRow(null); const { data, error: e } = await supabase.from(section.table).select("*").limit(100); if (e) setError(e.message); setRows((data ?? []) as Row[]); setLoading(false); }
  useEffect(() => { void loadSummaries(); }, []); useEffect(() => { void load(); if (!supabase) return; const ch = supabase.channel(`admin-${section.table}`).on("postgres_changes", { event: "*", schema: "public", table: section.table }, () => { void load(); void loadSummaries(); }).subscribe(); return () => { void supabase.removeChannel(ch); }; }, [section.table]);
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return n ? rows.filter(r => JSON.stringify(r).toLowerCase().includes(n)) : rows; }, [rows, query]);
  const columns = useMemo(() => { const keys = new Set<string>(); filtered.slice(0, 30).forEach(r => Object.keys(r).forEach(k => keys.add(k))); return [...keys].filter(k => k !== "id").slice(0, 9); }, [filtered]);
  const total = summaries.reduce((a, b) => a + b.count, 0), users = summaries.find(s => s.key === "profiles")?.count ?? 0, tickets = summaries.find(s => s.key === "support")?.count ?? 0;

  async function loadBilling(uid: string) { if (!supabase || !uid) return; const [{ data: p, error: pe }, { data: u, error: ue }, { data: sub, error: se }] = await Promise.all([supabase.from("profiles").select("plan_id").eq("user_id", uid).maybeSingle(), supabase.from("subscription_usage").select("*").eq("user_id", uid).order("usage_month", { ascending: false }).limit(1).maybeSingle(), supabase.from("subscriptions").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(1).maybeSingle()]); if (pe || ue || se) { setError((pe || ue || se)?.message ?? "Unable to load billing data."); return; } const planId = text(p?.plan_id) || text(sub?.plan_id) || "free"; setBilling({ userId: uid, planId, aiUsed: text(u?.ai_requests_used) || "0", aiLimit: text(u?.ai_requests_limit) || String(plans.find(x => x.id === planId)?.aiLimit ?? 0), storageUsed: text(u?.storage_mb_used) || "0", usageMonth: text(u?.usage_month) || new Date().toISOString().slice(0, 10), status: text(sub?.status) || "active", currentPeriodEnd: text(sub?.current_period_end).slice(0, 16) }); }
  async function openRow(r: Row) { setSelectedRow(r); setEditorDraft({ ...r }); const uid = text(r.user_id); if (uid && usageKeys.has(selected)) await loadBilling(uid); }
  async function saveBilling() { if (!canManage || !supabase || !billing.userId) return; setBillingBusy(true); setError(""); try { const plan = plans.find(p => p.id === billing.planId) ?? plans[0]; const now = new Date().toISOString(); const aiLimit = Math.max(0, Number(billing.aiLimit) || plan.aiLimit); const aiUsed = Math.max(0, Number(billing.aiUsed) || 0); const storage = Math.max(0, Number(billing.storageUsed) || 0); let e = (await supabase.from("profiles").update({ plan_id: plan.id, updated_at: now }).eq("user_id", billing.userId)).error; if (e) throw e; const { data: usage, error: ue } = await supabase.from("subscription_usage").select("id").eq("user_id", billing.userId).eq("usage_month", billing.usageMonth).maybeSingle(); if (ue) throw ue; const payload = { user_id: billing.userId, ai_requests_used: aiUsed, ai_requests_limit: aiLimit, storage_mb_used: storage, usage_month: billing.usageMonth, updated_at: now }; e = usage?.id ? (await supabase.from("subscription_usage").update(payload).eq("id", usage.id)).error : (await supabase.from("subscription_usage").insert(payload)).error; if (e) throw e; const { data: sub, error: se } = await supabase.from("subscriptions").select("id").eq("user_id", billing.userId).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (se) throw se; if (sub?.id) { e = (await supabase.from("subscriptions").update({ plan_id: plan.id, status: billing.status, current_period_end: billing.currentPeriodEnd ? new Date(billing.currentPeriodEnd).toISOString() : null, updated_at: now }).eq("id", sub.id)).error; if (e) throw e; } setNotice("Plan and usage saved successfully."); await load(); await loadSummaries(); } catch (e) { setError(e instanceof Error ? e.message : "Plan and usage could not be saved."); } finally { setBillingBusy(false); } }
  async function saveEditor() { if (!canManage || !supabase || !selectedRow?.id) return; setEditorBusy(true); setError(""); try { const value: Row = { ...editorDraft }; delete value.id; const { error: e } = await supabase.from(section.table).update(value).eq("id", text(selectedRow.id)); if (e) throw e; setNotice("Record saved successfully."); await load(); await loadSummaries(); } catch (e) { setError(e instanceof Error ? e.message : "Record could not be saved."); } finally { setEditorBusy(false); } }
  async function remove() { if (!canManage || !isSuperAdmin || !supabase || !selectedRow?.id || !window.confirm("Delete this record?")) return; const { error: e } = await supabase.from(section.table).delete().eq("id", text(selectedRow.id)); if (e) setError(e.message); else { setNotice("Record deleted."); await load(); await loadSummaries(); } }
  async function publishAnnouncement() { if (!canManage || !supabase || !announcement.title.trim() || !announcement.body.trim()) return; const { error: e } = await supabase.from("announcements").insert({ title: announcement.title.trim(), body: announcement.body.trim(), audience: announcement.audience, published_at: new Date().toISOString(), created_by: userId }); if (e) setError(e.message); else { setAnnouncement({ title: "", body: "", audience: "all" }); setAnnouncementOpen(false); setNotice("Announcement published."); await loadSummaries(); } }
  const resourceGroups = group === "All" ? groups : [group];

  return <section className="admin-control-center" aria-label="Admin control center">
    <div className="admin-hero"><div className="admin-hero-copy"><div className="admin-kicker"><ShieldCheck size={16} /> Secure administration</div><h2>Command Center</h2><p>One place to operate AthleteN: users, athlete data, verification, support, billing, product controls and audit history.</p><div className="admin-identity"><span className="admin-avatar">{role.slice(0, 2).toUpperCase()}</span><span><b>{role}</b><small>Signed in administrator</small></span></div></div><div className="admin-hero-actions"><div className="admin-live"><span /> Realtime connected</div><button className="btn" onClick={() => { void load(); void loadSummaries(); }} disabled={loading || summaryLoading}><RefreshCw size={15} /> {loading || summaryLoading ? "Refreshing..." : "Refresh all"}</button>{canManage&&<button className="btn primary" onClick={()=>setAnnouncementOpen(v=>!v)}><Megaphone size={15}/> Announcement</button>}</div></div>
    <div className="admin-stats"><article><span><Users size={17}/></span><div><small>Users</small><strong>{summaryLoading?"…":users}</strong><em>Profiles in platform</em></div></article><article><span><Database size={17}/></span><div><small>Total records</small><strong>{summaryLoading?"…":total}</strong><em>Across admin resources</em></div></article><article><span><FileCheck2 size={17}/></span><div><small>Plan & usage</small><strong>Ready</strong><em>Admin billing editor</em></div></article><article><span><Ticket size={17}/></span><div><small>Support tickets</small><strong>{summaryLoading?"…":tickets}</strong><em>All ticket records</em></div></article></div>
    {announcementOpen&&canManage&&<div className="admin-compose"><div><div><Megaphone size={18}/><h3>Publish announcement</h3></div><button className="icon-btn" onClick={()=>setAnnouncementOpen(false)}><X size={17}/></button></div><div className="admin-form-grid"><label>Title<input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></label><label>Audience<select value={announcement.audience} onChange={e=>setAnnouncement({...announcement,audience:e.target.value})}><option value="all">Everyone</option><option value="athletes">Athletes</option><option value="coaches">Coaches</option><option value="academies">Academies</option><option value="admins">Admins</option></select></label></div><label>Message<textarea value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})} rows={4}/></label><div className="inline-actions"><button className="btn primary" onClick={()=>void publishAnnouncement()} disabled={!announcement.title.trim()||!announcement.body.trim()}>Publish now</button></div></div>}
    <div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${section.label.toLowerCase()}...`}/></div><select value={group} onChange={e=>setGroup(e.target.value)}><option>All</option>{groups.map(g=><option key={g}>{g}</option>)}</select><span className="admin-result-count">{filtered.length} shown · {rows.length} loaded</span></div>
    <div className="admin-workspace"><aside className="admin-resource-nav"><div className="admin-nav-title">Resources</div>{resourceGroups.map(g=><div key={g} className="admin-nav-group"><span>{g}</span>{sections.filter(s=>s.group===g).map(s=><button key={s.key} className={s.key===selected?"active":""} onClick={()=>{setSelected(s.key);setQuery("");setSelectedRow(null);}}><span>{s.label}</span><b>{summaries.find(x=>x.key===s.key)?.count??"—"}</b><ChevronRight size={14}/></button>)}</div>)}</aside>
      <div className="admin-content"><div className="admin-section-head"><div><span className="admin-section-label">{section.group}</span><h3>{section.label}</h3><p>{canManage?"Administrative controls are enabled for your role.":"Read-only view."}</p></div><div className="admin-permission"><span className={canManage?"ok":"limited"}>{canManage?"Manage":"Read only"}</span><small>{isSuperAdmin?"Super administrator":role}</small></div></div>
      {error&&<div className="admin-alert error"><AlertTriangle size={17}/><span>{error}</span><button onClick={()=>setError("")}><X size={15}/></button></div>}{notice&&<div className="admin-alert success"><Check size={17}/><span>{notice}</span><button onClick={()=>setNotice("")}><X size={15}/></button></div>}
      {usageKeys.has(selected)&&<div className="admin-compose" style={{marginBottom:16}}><div><div><Database size={18}/><h3>Plan & usage controls</h3></div><span className="admin-section-label">Select a record below, or enter a user ID</span></div><div className="admin-form-grid"><label>User ID<input value={billing.userId} onChange={e=>setBilling({...billing,userId:e.target.value})} placeholder="User UUID"/></label><label>Plan<select value={billing.planId} onChange={e=>{const id=e.target.value;setBilling({...billing,planId:id,aiLimit:String(plans.find(p=>p.id===id)?.aiLimit??0)})}}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} ({p.id})</option>)}</select></label><label>AI requests used<input type="number" min="0" value={billing.aiUsed} onChange={e=>setBilling({...billing,aiUsed:e.target.value})}/></label><label>AI requests limit<input type="number" min="0" value={billing.aiLimit} onChange={e=>setBilling({...billing,aiLimit:e.target.value})}/></label><label>Storage MB used<input type="number" min="0" value={billing.storageUsed} onChange={e=>setBilling({...billing,storageUsed:e.target.value})}/></label><label>Usage month<input type="date" value={billing.usageMonth} onChange={e=>setBilling({...billing,usageMonth:e.target.value})}/></label><label>Status<select value={billing.status} onChange={e=>setBilling({...billing,status:e.target.value})}><option value="active">active</option><option value="trialing">trialing</option><option value="past_due">past_due</option><option value="canceled">canceled</option><option value="incomplete">incomplete</option></select></label><label>Current period end<input type="datetime-local" value={billing.currentPeriodEnd} onChange={e=>setBilling({...billing,currentPeriodEnd:e.target.value})}/></label></div><div className="inline-actions"><button className="btn primary" onClick={()=>void saveBilling()} disabled={!canManage||billingBusy||!billing.userId}>{billingBusy?"Saving...":"Save plan & usage"}</button></div></div>}
      {loading?<div className="admin-loading"><span/><span/><span/></div>:filtered.length?<div className="admin-table-shell"><table><thead><tr><th>Record</th>{columns.map(k=><th key={k}>{k.replace(/_/g," ")}</th>)}<th>Open</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={text(r.id)||i}><td><strong>{text(r.id).slice(0,8)||"record"}</strong></td>{columns.map(k=><td key={k}>{shown(r[k]).slice(0,120)}</td>)}<td><button className="btn" onClick={()=>void openRow(r)}>Open</button></td></tr>)}</tbody></table></div>:<div className="empty"><strong>No records found.</strong><p>Try another search or refresh.</p></div>}
      {selectedRow&&<div className="admin-compose" style={{marginTop:16}}>
        <div><div><Database size={18}/><h3>Record editor</h3></div><button className="icon-btn" onClick={()=>setSelectedRow(null)}><X size={17}/></button></div>
        <p>Edit this record using structured controls. System IDs and timestamps are protected.</p>
        <div className="admin-form-grid">
          {Object.entries(editorDraft).map(([key,value]) => {
            const readOnly = !canManage || readOnlyEditorKeys.has(key) || (key === "user_id" && selected === "profiles");
            const label = editorLabel(key);
            if (key === "role") return <label key={key}>{label}<select value={text(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value}))} disabled={readOnly}><option value="athlete">Athlete</option><option value="coach">Coach</option><option value="academy">Academy</option><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select></label>;
            if (key === "plan_id") return <label key={key}>{label}<select value={text(value)||"free"} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value}))} disabled={readOnly}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} ({p.id})</option>)}</select></label>;
            if (typeof value === "boolean") return <label key={key} style={{display:"flex",alignItems:"center",gap:10}}><input type="checkbox" checked={value} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.checked}))} disabled={readOnly}/><span>{label}</span></label>;
            if (Array.isArray(value)) return <label key={key}>{label}<textarea rows={4} value={arrayEditorText(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value.split("\n").map(v=>v.trim()).filter(Boolean)}))} disabled={readOnly} placeholder="One item per line"/></label>;
            if (value && typeof value === "object") return <label key={key}>{label}<textarea rows={4} value={objectEditorText(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:parseObjectEditorText(e.target.value)}))} disabled={readOnly} placeholder="One field per line: key=value"/></label>;
            if (isLongEditorKey(key)) return <label key={key}>{label}<textarea rows={4} value={text(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value}))} disabled={readOnly}/></label>;
            if (isDateEditorKey(key)) return <label key={key}>{label}<input type={key.includes("at")||key.includes("time")||key.includes("period_end")?"datetime-local":"date"} value={text(value).slice(0,key.includes("at")||key.includes("time")||key.includes("period_end")?16:10)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value||null}))} disabled={readOnly}/></label>;
            if (typeof value === "number" || (value === null && isNumericEditorKey(key))) return <label key={key}>{label}<input type="number" value={text(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value===""?null:Number(e.target.value)}))} disabled={readOnly}/></label>;
            return <label key={key}>{label}<input value={text(value)} onChange={e=>setEditorDraft(d=>({...d,[key]:e.target.value===""?null:e.target.value}))} disabled={readOnly}/></label>;
          })}
        </div>
        <div className="inline-actions"><button className="btn primary" onClick={()=>void saveEditor()} disabled={!canManage||editorBusy}>{editorBusy?"Saving...":"Save record"}</button>{isSuperAdmin&&<button className="btn" onClick={()=>void remove()}>Delete</button>}</div>
      </div>}
      </div></div>
  </section>;
}
