import { useEffect, useMemo, useState } from "react";
import { Activity, Award, BarChart3, CheckCircle2, ChevronRight, Crown, Link2, Plus, ShieldCheck, Users, Weight, XCircle } from "lucide-react";
import { supabase } from "../../lib/supabase";
import type { Profile } from "../../types";
import "./coach-academy.css";

type Props = { profile: Profile; setToast: (toast: { type: "success" | "error" | "warning"; message: string } | null) => void };
type Athlete = Pick<Profile,"user_id"|"full_name"|"username"|"belt"|"weight_kg"|"competition_weight_category"|"discipline"|"academy_id"|"coach_user_id"> & { id?: string };
type Link = { id:string; coach_user_id:string; athlete_user_id:string; academy_id:string|null; status:string };
type Approval = { id:string; athlete_user_id:string; coach_user_id:string; academy_id:string|null; request_type:string; current_value:string|null; requested_value:string; athlete_weight_kg:number|null; notes:string|null; status:string; created_at:string };
type Seat = { id:string; academy_id:string; coach_user_id:string; seat_type:string; activation_fee:number; monthly_fee:number; status:string };
type Academy = { id:string; name:string; city:string|null; state:string|null; country:string|null; owner_user_id:string; status:string };
type Member = { user_id:string; role:string; status:string; joined_at:string; profile?:Profile };
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const initials=(name?:string)=>String(name||"Coach").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
export default function CoachAcademyDashboard({profile,setToast}:Props){
 const [tab,setTab]=useState<"overview"|"athletes"|"approvals"|"academy"|"billing">("overview"); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [athletes,setAthletes]=useState<Athlete[]>([]); const [links,setLinks]=useState<Link[]>([]); const [approvals,setApprovals]=useState<Approval[]>([]); const [seats,setSeats]=useState<Seat[]>([]); const [academy,setAcademy]=useState<Academy|null>(null); const [members,setMembers]=useState<Member[]>([]); const [username,setUsername]=useState(""); const [newAcademy,setNewAcademy]=useState("");
 const userId=profile.user_id||""; const academyId=profile.academy_id||null; const isAcademy=profile.role==="academy_admin"||Boolean(academyId); const planId=profile.plan_id;
 async function load(){if(!userId||!supabase)return;setBusy(true);try{const linkQuery=await supabase.from("coach_athlete_links").select("*").eq("coach_user_id",userId).eq("status","active");if(linkQuery.error)throw linkQuery.error;const nextLinks=(linkQuery.data||[]) as Link[];setLinks(nextLinks);const ids=nextLinks.map(x=>x.athlete_user_id);if(ids.length){const q=await supabase.from("profiles").select("user_id,id,full_name,username,belt,weight_kg,competition_weight_category,discipline,academy_id,coach_user_id").in("user_id",ids);if(q.error)throw q.error;setAthletes((q.data||[]) as Athlete[]);}else setAthletes([]);const aq=await supabase.from("coach_approval_requests").select("*").eq("coach_user_id",userId).order("created_at",{ascending:false});if(aq.error)throw aq.error;setApprovals((aq.data||[]) as Approval[]);if(academyId){const ac=await supabase.from("academies").select("*").eq("id",academyId).single();if(!ac.error)setAcademy(ac.data as Academy);const sq=await supabase.from("academy_coach_seats").select("*").eq("academy_id",academyId).order("created_at");if(!sq.error)setSeats((sq.data||[]) as Seat[]);const mq=await supabase.from("academy_memberships").select("user_id,role,status,joined_at").eq("academy_id",academyId).eq("status","active");if(!mq.error){const ms=(mq.data||[]) as Member[];if(ms.length){const ids2=ms.map(x=>x.user_id);const pq=await supabase.from("profiles").select("*").in("user_id",ids2);const map=new Map((pq.data||[]).map((p:Profile)=>[p.user_id,p]));setMembers(ms.map(m=>({...m,profile:map.get(m.user_id)})));}else setMembers([]);}}}catch(e){setToast({type:"error",message:e instanceof Error?e.message:"Coach data could not be loaded."});}finally{setBusy(false);}}
 useEffect(()=>{void load();},[userId,academyId]); const pending=approvals.filter(x=>x.status==="pending"); const coachCount=seats.filter(x=>x.status==="active").length; const athleteCount=athletes.length; const weights=athletes.filter(a=>a.weight_kg!=null).map(a=>Number(a.weight_kg)); const averageWeight=weights.length?weights.reduce((s,n)=>s+n,0)/weights.length:0; const athleteMap=useMemo(()=>new Map(athletes.map(a=>[a.user_id,a])),[athletes]);
 async function connectAthlete(){if(!username.trim())return;setSaving(true);try{const {error}=await supabase.rpc("coach_connect_athlete",{p_username:username.trim(),p_academy_id:academyId});if(error)throw error;setUsername("");setToast({type:"success",message:"Athlete linked to your coaching roster."});await load();}catch(e){setToast({type:"error",message:e instanceof Error?e.message:"Athlete could not be linked."});}finally{setSaving(false);}}
 async function review(id:string,status:"approved"|"rejected"){setSaving(true);try{const {error}=await supabase.rpc("review_coach_approval",{p_request_id:id,p_status:status,p_notes:null});if(error)throw error;setToast({type:"success",message:`Approval ${status}.`});await load();}catch(e){setToast({type:"error",message:e instanceof Error?e.message:"Approval could not be completed."});}finally{setSaving(false);}}
 async function createAcademy(){if(!newAcademy.trim())return;setSaving(true);try{const {error}=await supabase.rpc("create_academy",{p_name:newAcademy.trim(),p_country:"India"});if(error)throw error;setNewAcademy("");setToast({type:"success",message:"Academy created and your coach account is now its primary operator."});await load();}catch(e){setToast({type:"error",message:e instanceof Error?e.message:"Academy could not be created."});}finally{setSaving(false);}}
 if(busy)return <section className="card panel coach-shell"><div className="coach-loading"><Activity className="spin"/><span>Loading your real coaching data…</span></div></section>;
 return <section className="coach-shell"><section className="coach-hero card"><div><span className="pill">{isAcademy?"Academy Command Center":"Individual Coach"}</span><h2>{isAcademy?(academy?.name||"Your Academy"):"Coach Command Center"}</h2><p>{isAcademy?"Run the academy, manage coaches, and coach athletes from one workspace.":"Manage your athlete roster now. Your coaching history can move into an Academy later without recreating athlete records."}</p></div><div className="coach-identity"><div className="coach-avatar">{initials(profile.full_name)}</div><div><strong>{profile.full_name||"Coach"}</strong><span>{isAcademy?"Primary / Operating Coach":"Individual Coach"}</span></div></div></section><div className="coach-tabs" role="tablist">{([["overview","Overview",BarChart3],["athletes","Athletes",Users],["approvals","Approvals",ShieldCheck],...(isAcademy?[["academy","Academy",Crown],["billing","Billing",Award]]:[])] as const).map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}><Icon size={16}/>{label}{id==="approvals"&&pending.length>0?<b>{pending.length}</b>:null}</button>)}</div>
 {tab==="overview"&&<><section className="metrics coach-metrics"><article className="metric card"><div className="metric-icon"><Users size={18}/></div><div><p>Athletes</p><strong>{athleteCount}</strong><small>Active coaching roster</small></div></article><article className="metric card"><div className="metric-icon"><Weight size={18}/></div><div><p>Average weight</p><strong>{averageWeight?`${averageWeight.toFixed(1)} kg`:"—"}</strong><small>From athlete profiles</small></div></article><article className="metric card"><div className="metric-icon"><ShieldCheck size={18}/></div><div><p>Pending approvals</p><strong>{pending.length}</strong><small>Belt or category decisions</small></div></article><article className="metric card"><div className="metric-icon"><Crown size={18}/></div><div><p>{isAcademy?"Coach seats":"Coach plan"}</p><strong>{isAcademy?coachCount:"₹149"}</strong><small>{isAcademy?"Active seats":"per month"}</small></div></article></section><section className="grid two"><article className="card panel coach-feature"><span className="eyebrow">Athlete-first workflow</span><h3>Weight → coach decision → competition category</h3><p>Athletes do not silently change category from a weight entry. The coach reviews the athlete's actual weight and records the competition category decision.</p><button className="btn primary" onClick={()=>setTab("athletes")}>Open roster <ChevronRight size={15}/></button></article><article className="card panel coach-feature"><span className="eyebrow">Governance</span><h3>Coach approvals stay auditable</h3><p>Belt changes and competition-weight-category decisions are recorded with the coach, athlete, academy context, and review status.</p><button className="btn" onClick={()=>setTab("approvals")}>Review approvals <ShieldCheck size={15}/></button></article></section></>}
 {tab==="athletes"&&<section className="card panel"><div className="panel-head"><div><span className="eyebrow">Roster</span><h3>{athleteCount} athlete{athleteCount===1?"":"s"}</h3><p>Only athletes actually linked to this coach are shown.</p></div><div className="coach-link-box"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Athlete username" aria-label="Athlete username"/><button className="btn primary" disabled={saving||!username.trim()} onClick={()=>void connectAthlete()}><Link2 size={15}/> Link athlete</button></div></div>{athletes.length?<div className="coach-athlete-grid">{athletes.map(a=><article className="card coach-athlete-card" key={a.user_id}><div className="coach-athlete-top"><div className="coach-avatar small">{initials(a.full_name)}</div><div><h3>{a.full_name||"Athlete"}</h3><span>@{a.username||"—"}</span></div><span className="tag">{a.discipline||"Taekwondo"}</span></div><div className="coach-athlete-stats"><div><small>Belt</small><strong>{a.belt||"Not set"}</strong></div><div><small>Weight</small><strong>{a.weight_kg!=null?`${a.weight_kg} kg`:"—"}</strong></div><div><small>Competition category</small><strong>{a.competition_weight_category||"Coach decision pending"}</strong></div></div><div className="inline-actions"><button className="btn" onClick={()=>setToast({type:"warning",message:"Athlete detail editing is intentionally limited to approved coach workflows."})}>View data</button><button className="plain" onClick={()=>setTab("approvals")}>Approvals <ChevronRight size={14}/></button></div></article>)}</div>:<div className="empty"><strong>No linked athletes yet</strong><span>Enter an athlete's AthleteN username above to create a real coaching relationship.</span></div>}</section>}
 {tab==="approvals"&&<section className="card panel"><div className="panel-head"><div><span className="eyebrow">Approval center</span><h3>{pending.length} pending</h3><p>Review belt promotions and competition-weight-category decisions.</p></div><ShieldCheck/></div>{pending.length?<div className="approval-list">{pending.map(r=>{const a=athleteMap.get(r.athlete_user_id);return <article className="approval-card" key={r.id}><div><span className="tag">{r.request_type==="belt_change"?"Belt change":"Weight category"}</span><h3>{a?.full_name||"Athlete"}</h3><p>{r.current_value||"Current value not set"} <ChevronRight size={14}/> <strong>{r.requested_value}</strong></p>{r.athlete_weight_kg!=null&&<small>Recorded athlete weight: {r.athlete_weight_kg} kg</small>}</div><div className="inline-actions"><button className="btn" disabled={saving} onClick={()=>void review(r.id,"rejected")}><XCircle size={15}/> Reject</button><button className="btn primary" disabled={saving} onClick={()=>void review(r.id,"approved")}><CheckCircle2 size={15}/> Approve</button></div></article>})}</div>:<div className="empty"><strong>No pending decisions</strong><span>New athlete approval requests will appear here.</span></div>}</section>}
 {tab==="academy"&&<section className="grid two"><article className="card panel"><span className="eyebrow">Organization</span><h3>{academy?.name||"Academy"}</h3><p>{academy?.city||"Location not set"}{academy?.state?`, ${academy.state}`:""}{academy?.country?`, ${academy.country}`:""}</p><div className="academy-kpis"><span><b>{members.filter(m=>m.role==="athlete").length}</b>Athletes</span><span><b>{members.filter(m=>m.role==="coach").length+members.filter(m=>m.role==="academy_admin").length}</b>Coaches</span><span><b>{coachCount}/2</b>Included seats used</span></div></article><article className="card panel"><span className="eyebrow">Academy upgrade</span><h3>Keep the same coach identity</h3><p>Your individual coach account can become the primary operator when an Academy is created. Existing athlete links remain on the same underlying accounts.</p>{isAcademy?<div className="notice">This coach is already linked to the Academy.</div>:<div className="coach-link-box"><input value={newAcademy} onChange={e=>setNewAcademy(e.target.value)} placeholder="Academy name"/><button className="btn primary" disabled={saving||!newAcademy.trim()||planId!=="academy"} onClick={()=>void createAcademy()}><Plus size={15}/> Create</button>{planId!=="academy"&&<small>Switch to the Academy plan before creating an Academy.</small>}</div>}</article></section>}
 {tab==="billing"&&<section className="card panel"><div className="panel-head"><div><span className="eyebrow">Coach seats</span><h3>2 included · additional seats are paid</h3><p>The first two coach seats are included with the Academy. Additional seats are ₹349 activation + ₹100/month. No payment is claimed here until a real payment provider is connected.</p></div><Award/></div><div className="seat-grid">{seats.length?seats.map((s,i)=><article className="seat-card card" key={s.id}><span className="pill">{s.seat_type==="included"?"Included":"Paid seat"}</span><strong>Coach seat {i+1}</strong><span>{s.status}</span><small>{s.seat_type==="paid"?`${money(s.activation_fee)} activation · ${money(s.monthly_fee)}/month`:"Included with Academy"}</small></article>):<div className="empty"><strong>No coach seats yet</strong><span>Seats appear after the Academy is created.</span></div>}</div></section>}
 </section>;
}
