-- Record the policy versions accepted at account creation.
-- The trigger reads non-sensitive signup metadata so email-confirmation flows
-- can record acceptance even before a session exists.

create table if not exists public.policy_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  source text not null default 'mobile_signup',
  unique (user_id)
);

alter table public.policy_acceptances enable row level security;

revoke all on table public.policy_acceptances from anon;
grant select, insert on table public.policy_acceptances to authenticated;

drop policy if exists "Users can read their own policy acceptance" on public.policy_acceptances;
create policy "Users can read their own policy acceptance"
  on public.policy_acceptances
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can record their own policy acceptance" on public.policy_acceptances;
create policy "Users can record their own policy acceptance"
  on public.policy_acceptances
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create or replace function public.record_signup_policy_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  terms_version text;
  privacy_version text;
  accepted_at_text text;
  parsed_accepted_at timestamptz;
begin
  terms_version := new.raw_user_meta_data ->> 'athleten_terms_accepted_version';
  privacy_version := new.raw_user_meta_data ->> 'athleten_privacy_accepted_version';
  accepted_at_text := new.raw_user_meta_data ->> 'athleten_policies_accepted_at';

  if terms_version is not null
     and privacy_version is not null
     and terms_version = privacy_version then
    begin
      parsed_accepted_at := coalesce(accepted_at_text::timestamptz, now());
    exception when others then
      parsed_accepted_at := now();
    end;

    insert into public.policy_acceptances (
      user_id,
      terms_version,
      privacy_version,
      accepted_at,
      source
    )
    values (
      new.id,
      terms_version,
      privacy_version,
      parsed_accepted_at,
      'mobile_signup'
    )
    on conflict (user_id) do update
      set terms_version = excluded.terms_version,
          privacy_version = excluded.privacy_version,
          accepted_at = excluded.accepted_at,
          source = excluded.source;
  end if;

  return new;
end;
$$;

revoke execute on function public.record_signup_policy_acceptance() from public, anon, authenticated;

drop trigger if exists on_auth_user_policy_acceptance on auth.users;
create trigger on_auth_user_policy_acceptance
  after insert on auth.users
  for each row
  execute function public.record_signup_policy_acceptance();
